{{wrap with="admin_page_layout.phtml" in="content_zone"}}

  {{include file="_admin_object/actions.phtml"/}}

  <div id="header">
    <h1>Requests</h1>
    {{include file='_admin/pager.phtml' items='{$#items}'/}}
  </div>

  <div id="body">

    {{list using="{$#items}" as="$item" counter="$counter" parity='$parity'}}

      <div class='list'>
        <table>
          <tr>
            <th width="5%">id</th>
            <th width="5%">Method / Path</th>
            <th width="5%">Code</th>
            <th width="10%">Time</th>
            <th width="5%">IP</th>
            <th width="20%">Request</th>
            <th width="20%">Response</th>
            <th width="5%">Действия</th>
          </tr>

          {{list:item}}
            <tr class="{$parity}">
              <td>{$item.id}</td>
              <td>{$item.method} {$item.path}</td>
              <td>{$item.code}</td>
              <td>{$item.time}</td>
              <td>{$item.ip}</td>
              <?php
                $gets = $item->get ? unserialize($item->get) : array();
                $posts = $item->post ? unserialize($item->post) : array();
                $cookies = $item->cookies ? unserialize($item->cookies) : array();
              ?>
              <td style="font-size:10px">
                <ul>
                  <li>
                    {{list using="{$gets}" as="$get" key="$key"}}
                      <strong>GET</strong>:
                      <ul>
                        {{list:item}}
                          <li>&nbsp;&nbsp;<b>{$key}</b> = {$get}</li>
                        {{/list:item}}
                      </ul>
                    {{/list}}
                  </li>
                  <li>
                    {{list using="{$posts}" as="$post" key="$key"}}
                      <strong>POST</strong>:
                      <ul>
                        {{list:item}}
                          <li>&nbsp;&nbsp;<b>{$key}</b> = {$post}</li>
                        {{/list:item}}
                      </ul>
                    {{/list}}
                  </li>
                  <li>
                    {{list using="{$cookies}" as="$cookie" key="$key"}}
                      <strong>COOKIES:</strong>
                      <ul>
                        {{list:item}}
                          <li>&nbsp;&nbsp;<b>{$key}</b> = {$cookie}</li>
                        {{/list:item}}
                      </ul>
                    {{/list}}
                  </li>
                </ul>
              </td>
              <td style="font-size:10px"><pre>{$item.response|clip:120,'...'|html}</pre></td>
              <td class='actions'>
                {{apply template="object_action_delete" item="{$item}"/}}
              </td>
            </tr>
          {{/list:item}}
          {{list:empty}}
            <div class="empty_list">Записи отсутствуют</div>
          {{/list:empty}}
        </table>
      </div>

    {{/list}}

  </div>

{{/wrap}}
