{{wrap with="admin_page_layout.phtml" in="content_zone"}}

  {{include file="_admin/selectors.phtml"/}}
  {{include file="_admin_object/actions.phtml"/}}

  <div id="header">
    <h1>User</h1>
    <div class="header_actions">
      {{apply template="object_action" action="create" is_link="true" title="Создать User"/}}
    </div>

    {{include file='_admin/pager.phtml' items='{$this->items}'/}}
  </div>

  <div id="body">

    {{list using="{$this->items}" as="$item" counter="$counter" parity='$parity'}}

      <div class='list'>
        <div class='list_actions'>
          {{apply template="selectors_button" action="delete" title="Удалить" /}}
        </div>
        <table>
          <tr>
            <th>{{apply template="selectors_toggler"/}}</th>
            <th>id
            {{include file='_admin/sort_by_column.phtml' field='id'/}}
            </th>
            <th>FB uid
            {{include file='_admin/sort_by_column.phtml' field='facebook_uid'/}}
            </th>
            <th>Name
              {{include file='_admin/sort_by_column.phtml' field='facebook_uid'/}}
            </th>
            <th>Times
            </th>
            <th>cip
            {{include file='_admin/sort_by_column.phtml' field='cip'/}}
            </th>
            <th>Действия</th>
          </tr>

          {{list:item}}
            <tr class="{$parity}">
              <td>{{apply template="selector" value="{$item.id}"/}}</td>
              <td>{$item.id}</td>
              <td><a href="https://facebook.com/profile.php?id={$item.facebook_uid}">{$item.facebook_uid}</td>
              <td><a href="/pages/{$item.id}/user/">{$item.name}</a></td>
              <td>
	              {$item.ctime|date:"d.m.Y H:i:s"} <br/>
	              {$item.utime|date:"d.m.Y H:i:s"}
              </td>
              <td>{$item.cip}</td>
              <td class='actions'>
                {{apply template="object_action_edit" item="{$item}"/}}
                {{apply template="object_action_delete" item="{$item}"/}}
              </td>
            </tr>
          {{/list:item}}
          {{list:empty}}
            <div class="empty_list">Пользователи отсутствуют</div>
          {{/list:empty}}
        </table>
        <div class='list_actions'>
          {{apply template="selectors_button" action="delete" title="Удалить" /}}
        </div>
      </div>

    {{/list}}

  </div>

{{/wrap}}
