<?
$this->menu = 'about';
$this->title = lmb_i18n("Live the life through other people's eyes");
?>
{{wrap with="layout.phtml"}}
{{into slot="css"}}
body {
padding-bottom: 100px;
}

.final-button {
margin-top: 40px;
}

.header-container {
margin-bottom: 35px;
width:100%;
height: 301px;
overflow: hidden;
background: url('/img/landing_title_bg.jpg');
background-size: cover;
position: relative;
}

.header-container .caption {
background-color: transparent;
position: absolute;
padding: 20px;
left: 15%;
top: 25%;
border-radius: 4px;
background: rgba(0, 0, 0, 0.8);
}

.header-container .caption h1,
.header-container .caption .lead {
margin: 0;
line-height: 1.25;
color: #fff;
text-shadow: 0 1px 1px rgba(0,0,0,.4);
font-weight:normal;
}

.header-container .caption .lead {
font-size:18px;
}

.header-container .caption .btn {
margin-top: 10px;
display: block;
width: 100px;
}

.phone-container {
margin-top: 80px;
width: 245px;
height: 520px;
position: absolute;
right: 10%;
top: 0;
}

.phone-container .phone-image {
background: url('/img/iphone.png');
background-size: contain;
background-repeat:no-repeat;
position: absolute;
top: 0;
left: 0;
right: 0;
bottom: 0;
}

.phone-container .phone-content {
position: absolute;
/*top: 85px;
right: 15px;
left: 20px;
bottom: 80px;
background: #FFF;
padding: 5px;*/

background: url('/img/coming-soon-screen.jpg');
background-size: cover;
top: 76px;
right: 17px;
left: 21px;
bottom: 78px;

color: #FFF;
font-weight: bold;
font-size: 20px;
text-align: center;
padding-top: 110px;
}

.coming-soon-bage {
border-radius: 4px;
background: rgba(0, 0, 0, 0.8);
padding: 10px;
margin-right: 10px;
margin-left: 10px;
}

/* Give some space on the sides of the floated elements so text doesn't run right into it. */
.featurette-image.pull-left {
margin-right: 40px;
}

.featurette-image.pull-right {
margin-left: 40px;
}

/* Thin out the marketing headings */
.features-heading {
font-size: 50px;
font-weight: 300;
line-height: 1;
letter-spacing: -1px;
}
{{/into}}

{{into slot="js"}}
var interesting_days = <?= json_encode($this->interesting_days); ?>;
{{/into}}

{{into slot="js_ready"}}
jQuery.jQueryRandom = 0;
jQuery.extend(jQuery.expr[":"], {
random: function(a, i, m, r) {
if (i == 0) {
jQuery.jQueryRandom = Math.floor(Math.random() * r.length);
};
return i == jQuery.jQueryRandom;
}
});

$('.wall-container').width(Math.ceil($(window).width()/200)*200);

$('#wall').masonry({
itemSelector: '#wall > li',
columnWidth: 200
});

/*var wall_selector = $('#wall');
var wall_moments_selector = wall_selector.children();
setInterval(function() {
var random_moment = $('#wall').children().sort(function(){
return Math.round(Math.random())-0.5
}).slice(0,1);
var random_moment_day = random_moment.data('day-id');

wall_moments_selector.removeClass('active');
wall_moments_selector.filter('[data-day-id='+random_moment_day+']').addClass('active');
}, 2000);*/
{{/into}}

{{into slot="content_fullwidth"}}
<div class="header-container">
	<div class="caption">
		<h1>One Day Of Mine</h1>
		<p class="lead">
			{{__ text="Live the life through other people\'s eyes"}}
			<a class="btn btn-large btn-success trigger_login" href="/pages/import">Try it</a>
		</p>
	</div>
</div>

<div class="row-fluid">
	<div class="span9 offset2">
		<h2 class="features-heading">{{__ text="Our main features"}}</h2>
	</div>
</div>
<div class="row-fluid">
	<div class="span3 offset2">
		<h3>{{__ text="Share a story, not photo"}}</h3>
		<p>{{__ text="Photos without a story are just beautiful pictures, we like to share stories, best moments of our life: travels, birthdays, parties and other meaningfull events."}}</p>
	</div>
	<div class="span3">
		<h3>{{__ text="Give new life to old photos"}}</h3>
		<p>{{__ text="People have tons of photos that are lost in time, give them new life, make stories out of them and share them with friends."}}</p>
	</div>
	<div class="span3">
		<h3>{{__ text="Magic"}}</h3>
		<p>{{__ text="It’s an easy-to-use tool, just connect your social profiles and enjoy the magic."}}</p>
	</div>
</div>

<hr />

<div class="row-fluid">
	<div class="span9 offset2">
		<h2 class="features-heading">{{__ text="How does it work?"}}</h2>
	</div>
</div>
<div class="row-fluid featurette clearfix">
	<div class="span9 offset2">
		<img class="featurette-image img-polaroid pull-right" src="/img/sign-up-screen.png">
		<h3>{{__ text="Sign up"}}</h3>
		<p>{{__ text="No need to enter any information, we will use your Facebook profile"}}</p>
		<a class="btn btn-success trigger_login" href="/pages/import">{{__ text="Sign up"}}</a>
	</div>
</div>
<div class="row-fluid featurette clearfix">
	<div class="span9 offset2">
		<hr />
		<img class="featurette-image img-polaroid pull-left" src="/img/create-day-screen.png">
		<h3>{{__ text="Create day"}}</h3>
		<p>You can <a class="trigger_login" href="/pages/import#create_empty_day">create empty day</a> or <a class="trigger_login" href="/pages/import">import your photo</a> from Flickr, Instagram and Facebook.</p>
	</div>
</div>
<div class="row-fluid featurette clearfix">
	<div class="span9 offset2">
		<hr />
		<img class="featurette-image img-polaroid pull-right" src="/img/edit-day-screen.png">
		<h3>{{__ text="Editing days is simple as never before"}}</h3>
		<p>{{__ text="You can arrange moments by changing time, selecting cover, editing images and many other."}}</p>
	</div>
</div>
<div class="row-fluid featurette clearfix">
	<div class="span9 offset2">
		<hr />
		<img class="featurette-image img-polaroid pull-left" src="/img/add-moment-screen.png">
		<h3>{{__ text="Add moments"}}</h3>
		<p>{{__ text="You can upload pictures from PC, your cell phone, or import them from Flickr, Instagram and Facebook. You can even upload image by dragging it from your desktop onto empty moment."}}</p>
	</div>
</div>
<div class="row-fluid featurette clearfix">
	<div class="span9 offset2">
		<hr />
		<img class="featurette-image img-polaroid pull-right" src="/img/describe-moment-screen.png">
		<h3>{{__ text="Add moments descriptions"}}</h3>
		<p>{{__ text="You can leave a short description for the greater expression emotions of the moment."}}</p>
	</div>
</div>
<div class="row-fluid featurette clearfix">
	<div class="span9 offset2">
		<hr />
		<img class="featurette-image img-polaroid pull-left" src="/img/share-screen.png">
		<h3>{{__ text="Share it"}}</h3>
		<p>{{__ text="Post your day on Facebook"}}</p>
	</div>
</div>
<div class="row-fluid featurette clearfix">
	<div class="span9 offset2">
		<hr />
		<img class="featurette-image img-polaroid pull-right" src="/img/likes-screen.png">
		<h3>{{__ text="Get interest"}}</h3>
		<p>{{__ text="Likes! Everybody loves them."}}</p>
	</div>
</div>
<div class="text-center final-button">
	<a class="btn btn-large btn-success trigger_login" href="/pages/import">{{__ text="Awesome! I have stories to tell!"}}</a>
</div>
{{/into}}
{{/wrap}}
