<?
$this->menu = '';
?>
{{wrap with="layout.phtml"}}
{{into slot="content"}}
<div class="hero-unit">
    <h1>Start import days&hellip;</h1>
    <div style="padding-top: 50px">
        <a class="btn btn-large btn-main" href="https://api.instagram.com/oauth/authorize/?client_id={$#instagram.client_id}&redirect_uri={$#instagram.redirect_url}&response_type=token">
            &hellip;from Instagram
            <i class="icon icon-large icon-camera-retro"></i>
        </a>
        <a class="btn btn-large btn-main disabled" href="/pages/import">
            &hellip;from Flickr
            <i class="icon icon-large icon-camera"></i>
        </a>
        <a class="btn btn-large btn-main disabled" href="/pages/import">
            &hellip;from Facebook
            <i class="icon icon-large icon-facebook-sign"></i>
        </a>
        <br class="clearFix"/>
    </div>
</div>

{{/into}}
{{/wrap}}
