<?
$this->menu = 'Create day';
$this->menu = 'create_day';
?>
{{wrap with="layout.phtml"}}
  {{into slot="js_ready"}}
    $('#day_create').click(function() {
      API.post('days/start', {title:'My day', type:'Working day'}).success(function(resp) {
        window.location.href= '/pages/'+resp.data.result.id+'/day';
      }).send();
    });
  {{/into}}
  {{into slot="content"}}
    <div class="hero-unit">
      <div class="text-center" style="padding-top: 50px;">
        <a class="btn btn-large btn-main" id="day_create">
          <i class="icon icon-large icon-edit"></i>
          Create day from scratch
        </a>
      </div>
    </div>
  {{/into}}
{{/wrap}}
