<?
$this->menu = '';
?>
{{wrap with="layout.phtml"}}
{{into slot="content"}}
<div class="hero-unit">
    <h1>Start import days&hellip;</h1>
    <div style="padding-top: 30px">
        <a class="btn btn-large btn-main" href="https://api.instagram.com/oauth/authorize/?client_id={$#instagram.client_id}&redirect_uri={$#instagram.redirect_url}&response_type=token">
            &hellip;from Instagram
            <i class="icon icon-large icon-camera-retro"></i>
        </a>
        <a class="btn btn-large btn-main disabled" href="/pages/import">
            &hellip;from Flickr
            <i class="icon icon-large icon-camera"></i>
        </a>
        <a class="btn btn-large btn-main disabled" href="/pages/import">
            &hellip;from Facebook
            <i class="icon icon-large icon-facebook-sign"></i>
        </a>
        <br class="clearFix"/>
    </div>
		<h1> or </h1>
		<div style="padding-top: 30px">
			<a class="btn btn-large btn-main create-empty-action">
				&hellip;create empty
				<i class="icon icon-large icon-edit"></i>
			</a>
		</div>
</div>
{{/into}}
{{into slot="js_ready"}}
	$('.create-empty-action').click(function() {
		API.post('days/start', {title:'My day',type:'Working day'}).success(function(resp) {
			window.location.href= '/pages/'+resp.data.result.id+'/day';
		}).send();
	});
{{/into}}
{{/wrap}}
