<?
$this->title = "Search for days";
$this->menu = 'search';
?>
{{wrap with="layout.phtml"}}
{{into slot="content"}}
		<h1>Search for days</h1>
		<form class="form-search" style="margin-top:15px">
		    <input type="text" class="input-xlarge search-query">
		    <button type="submit" class="btn">Search</button>
		</form>
		<div id="days"></div>
{{/into}}
{{into slot="js_ready"}}
		$('.form-search').submit(function() {
				var req = API.request('POST', 'days/search', {query:$('.search-query').val()}).success(function(response) {
						$('#days').html();
						var source = Template.prepareTemplate($('#days_list'));
						Template.renderElement(source, $('#days'), {days:response.data.result});
				}).send();
				return false;
    });
{{/into}}
{{/wrap}}
