<?
$this->title = "Search for days";
$this->menu = 'search';
?>
{{wrap with="layout.phtml"}}
{{into slot="content"}}
  <div class="row">
    <div class="span11">
  		<h1>Search for days</h1>
  		<form class="form-search" style="margin-top:15px">
  		    <input type="text" class="input-xlarge search-query">
  		    <button type="submit" class="btn">Search</button>
  		</form>
  		<div id="days"></div>
    </div>
  </div>
{{/into}}
{{into slot="js_ready"}}
		$('.form-search').submit(function() {
				if($('' == '.search-query').val())
						return;
				var req = API.request('POST', 'days/search', {query:$('.search-query').val()}).success(function(response) {
						$('#days').html();
						if(0 == response.data.result.length)
						{
								$('#days').html("<p>We can't find any days by your query</p>");
						}
						else
						{
								var source = Template.prepareTemplate($('#days_list'));
								Template.renderElement(source, $('#days'), {days:response.data.result});
						}
				}).send();
				return false;
    });
{{/into}}
{{/wrap}}
