<?
$this->title = "Search for days";
$this->menu = 'search';
?>
{{wrap with="layout.phtml"}}
  {{into slot="js_ready"}}
    (function() {
      var search_form_selector = $('.form-search');
      var search_form_query_selector = search_form_selector.find('.search-query');
      var search_form_submit_selector = search_form_selector.find('button');
      var search_result_selector = $('.search-result');

      search_form_query_selector.attachValidator({
        button: search_form_submit_selector,
        maxLength: 100,
        minLength: 3,
        messages: {
          empty: 'Search query is empty',
          minLength: 'Search query is too short',
          maxLength: 'Search query is too long'
        }
      });

      search_form_selector.submit(function(event) {
        var search_request = API.request('POST', 'days/search', {
          query: search_form_query_selector.val()
        });

        search_request.success(function(response) {
          search_result_selector.html();
          if(response.data.result.length === 0)
          {
            search_result_selector.html("<p>We can't find any days by your query</p>");
          }
          else
          {
            var source = Template.prepareTemplate($('#days_list_template'));
            Template.renderElement(source, search_result_selector, {days:response.data.result});
          }
        })

        search_request.send();

        return false;
      });
    })();
  {{/into}}
  {{into slot="content"}}
    <h1 class="page-title">Search for days</h1>
    <div class="row-fluid">
      <form class="form-search days-search-form">
        <input type="text" autofocus class="input-xlarge search-query span5">
        <button type="submit" class="btn btn-small">Search</button>
      </form>
    </div>
    <div class="search-result"></div>
  {{/into}}
{{/wrap}}
