<?
$this->title = "Interesting days";
$this->menu = 'explore';
?>
{{wrap with="layout.phtml"}}
{{into slot="content"}}
<ul class="nav nav-pills">
    <li class="active">
        <a href="/pages/days_interesting">Interesting</a>
    </li>
    <li><a href="/pages/days_new">New</a></li>
    <li><a href="/pages/days_live">Live</a></li>
    <li><a href="/pages/days_search">Search</a></li>
</ul>
<h1>Interesting days</h1>
{{/into}}
{{/wrap}}
