<?
$this->menu = '';
?>
{{wrap with="layout.phtml"}}
{{into slot="content"}}
<div class="hero-unit">
    <h1>One Day Of Mine</h1>
		<p class="lead">Live the life through other people's eyes</p>
    <ul class="unstyled">
        <li>
            <i class="icon-large icon-camera-retro"></i>
            new life for old photos
        </li>
        <li>
            <i class="icon-large icon-magic"></i>
            easy to use: just click next and enjoy our magic
        </li>
        <li>
            <i class="icon-large icon-eye-open"></i>
            look at life through the eyes of different people
        </li>
        <li>
            <i class="icon-large icon-group"></i>
            gain interest of other people by publishing days from your life
        </li>
        <li>
            <hr/>
            <a href="/pages/first_import" class="btn btn-large">Ready! Set! Go!</a>
        </li>
    </ul>

</div>
{{/into}}
{{/wrap}}