<?
$this->menu = '';
?>
{{wrap with="layout.phtml"}}
{{into slot="css"}}
.followers-list li {
  float:left;
  margin-right:3px;
}
.followers-list li img {
	width:32px;
	height:32px;
}

blockquote small::before {
	content: '';
}

blockquote small {
	margin-top:5px;
	margin-left:43px;
}

blockquote small img, blockquote p img{
	width:133px;
	height:133px;
	margin-right:7px;
}

.userpic {
	width:32px;
	height:32px;
	margin-top:13px;
}

.my-label {
	color: #bbb;
}
{{/into}}
{{into slot="content"}}
<div class="row">
		<div class="span8">
				<h3>News</h3>
				<ul class="unstyled">
						<li>
                    <p>
                        <img src="http://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Kutuzov_by_Volkov.jpg/240px-Kutuzov_by_Volkov.jpg" class="userpic"/>
		                    <a href="/pages/5/user">Мишка &quot;одноглазый&quot;</a> создал новый день <a href="/pages/2/day">Катаемся, с друзьями, в Альпах</a>
                    </p>
						</li>
            <li>
		                <p>
                      <img src="http://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Helene_Paris_David.jpg/220px-Helene_Paris_David.jpg" class="userpic"/>
                      <a href="#">Парис из Трои</a> добавил момент в день <a href="">Подарочный конь от данайцев</a>
			              </p>
                    <small style="margin-top:5px;">
		                  <img src="http://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Trojan_horse_%C3%87anakkale.jpg/220px-Trojan_horse_%C3%87anakkale.jpg">
                    </small>
            </li>
            <li>
                    <p>
                        <img src="http://images.instagram.com/profiles/profile_1450621_75sq_1360187746.jpg" class="userpic"/>
                        <a href="#">Joe Qinstein</a> добавил 2 момента в день <a href="">В гостях у Рерихов в Индийских Гималаях</a>
                    </p>
	                  <small style="margin-top:5px;">
                      <img src="http://onedayofmine-stage.s3.amazonaws.com/days/7/af5c17ab3caee0279d62e4daa21bc2c41c82c282_532.jpeg">
											<img src="http://onedayofmine-stage.s3.amazonaws.com/days/7/aa9df1b2ed4a017dd9490d25c0b2978e1d1fbd37_532.jpeg">
                    </small>
            </li>
            <li>
                    <p>
                        <img src="http://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/DelarocheNapoleon.jpg/220px-DelarocheNapoleon.jpg" class="userpic"/>
                        <a href="">Наполеон (Боня Островной)</a> прокомментировал ваш день "<a href="">Смог в Москве 2010</a>"
                        <p style="margin-left:42px">
                          Мисье, вы ничего не знаете о смогах в Москве. Вот помню в прошлом году, мы с ребятами...
                        </p>
                    </p>
                    <small>5 фев в 18:15</small>
            </li>
            <li>
		            <img src="http://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/DelarocheNapoleon.jpg/220px-DelarocheNapoleon.jpg" class="userpic"/>
                <a href="">Наполеон (Боня Островной)</a> ответил на ваш комментарий к дню "<a href="">Смог в Москве 2010</a>"
                <blockquote style="margin-left:39px;font-size:14px">Ни разу не видел такого! Хоррор можно было снимать.</blockquote>
                <p style="margin-left:42px">
                    Мисье, вы ничего не знаете о смогах в Москве. Вот помню в прошлом году, мы с ребятами зашли в Москву. А ее одноглазик запалил. Пожарища, пахнет жутко, и не видно нихрена. Но пробок не было, что характерно!
                </p>
                <small>5 фев в 18:15</small>
            </li>
				</ul>
		</div>
		<div class="span4">
				<div class="span4">
						<h5>Following&nbsp;&nbsp;<small>7</small></h5>
						<ul class="unstyled  followers-list">
								<li><img src="http://images.instagram.com/profiles/profile_1450621_75sq_1360187746.jpg"/></li>
                <li><img src="http://images.instagram.com/profiles/profile_39989663_75sq_1360449330.jpg"/></li>
                <li><img src="http://images.instagram.com/profiles/profile_47719173_75sq_1358861573.jpg"/></li>
                <li><img src="http://images.instagram.com/profiles/profile_299349163_75sq_1359754073.jpg"/></li>
						</ul>
				</div>
        <div class="span4">
		        <h5>Followers&nbsp;&nbsp;<small>3</small></h5>
            <ul class="unstyled followers-list">
                <li><img src="http://images.instagram.com/profiles/profile_10518982_75sq_1357688182.jpg"/></li>
                <li><img src="http://images.instagram.com/profiles/profile_299349163_75sq_1359754073.jpg"/></li>
                <li><img src="http://images.instagram.com/profiles/profile_20499101_75sq_1359408582.jpg"/></li>
                <li><img src="http://images.instagram.com/profiles/profile_1450621_75sq_1360187746.jpg"/></li>
                <li><img src="http://images.instagram.com/profiles/profile_39989663_75sq_1360449330.jpg"/></li>
                <li><img src="http://images.instagram.com/profiles/profile_47719173_75sq_1358861573.jpg"/></li>
            </ul>
        </div>
		</div>
</div>
<script>
    $('.tool').tooltip();
</script>
{{/into}}
{{/wrap}}
