<?
$this->title = "Find and invite people";
$this->menu = 'me';
?>
{{wrap with="layout.phtml"}}
{{into slot="content"}}
<div class="row">
		<div class="span6">
				<h1>Find</h1>
				<form class="form-search" style="margin-top:15px">
				    <input type="text" class="input-xlarge search-query">
				    <button type="submit" class="btn">Search</button>
				</form>
				<div id="search-result"></div>
		</div>
    <div class="span6">
        <h1>Invite</h1>
        <div id="invite-result"></div>
		</div>
</div>
{{/into}}
{{into slot="js_ready"}}

		API.request('POST', 'social/facebook_friends').success(function(response) {
				var users = response.data.result;
				$.each(users, function(i, user) {
						users[i].image = user.image_150;
						users[i].btn_attr = 'uid';
						users[i].btn_value = user.uid;
						users[i].btn_text = 'Invite';
						users[i].btn_class = 'btn-info';
				});
				Template.renderElement(Template.prepareTemplate($('#users_list')), $('#invite-result'), {users:users});
		}).send();

		$('.form-search').submit(function() {
				var req = API.request('POST', 'users/search', {query:$('.search-query').val()}).success(function(response) {
						$('#search-result').html();
						var users = response.data.result;
						$.each(users, function(i, user) {
								console.log(user);
								users[i].image = user.image_96;
								users[i].btn_attr = 'uid';
								users[i].btn_value = user.uid;
								users[i].btn_text = 'Follow';
								users[i].btn_class = '';
						});
						Template.renderElement(Template.prepareTemplate($('#users_list')), $('#search-result'), {users:users});
				}).send();
				return false;
		});
{{/into}}
{{/wrap}}
