{{wrap with="layout.phtml"}}
{{into slot="css"}}
{{/into}}
{{into slot="content"}}
        <div>
            <h3>Import from Instagram</h3>

            <div class="progress" style="display:none">
                <div class="bar bar-danger" style="width: 0%;"></div>
                <div class="bar bar-warning" style="width: 0%;"></div>
                <div class="bar bar-success" style="width: 0%;"></div>
            </div>

            <center><a href="https://api.instagram.com/oauth/authorize/?client_id={$#instagram.client_id}&redirect_uri={$#instagram.redirect_url}&response_type=token"
               class="btn btn-danger btn-large" style="display:none">
                Step 1 of 3 <i class="icon-white icon-forward"></i>
            </a></center>

            <div class="well cant alert alert-danger" style="display:none">
		            Sorry. You have no days with 3 or more photos.
            </div>

            <div class="days"></div>
        </div>
{{/into}}
{{into slot="templates"}}
	<script id="day-item" type="text/x-handlebars-template">
      <div day_pos="[[day_position]]" class="well">
          <h4 class="time">[[time]]</h4>
		      <div class="step2">
				      <ul class="thumbnails">
							[[#moments]]
				          <li style="width:160px;">
						          <div class="thumbnail">
								          <div class="img-wrap"  style="background:#fff">
                              <img src="[[images.thumbnail.url]]" class="img-rounded" alt="[[caption.text]]" title="[[caption.text]]"/>
                          </div>
                          <center style="padding-top:10px">
                              <button class="btn btn-info remove-photo-action" day_pos="[[../day_position]]" moment_id="[[id]]">Skip</button>
                          </center>
						          </div>
				          </li>
					    [[/moments]]

				      </ul>
			        <center><button class="btn btn-warning btn-large analyze-action">
				        Step 2 of 3 <i class="icon-white icon-forward"></i> </button></center>
				  </div>
		      <div class="step3" style="display:none">
						<form class="form-horizontal">
                <div class="control-group">
                    <label class="control-label " for="type_[[day_position]]">Day type</label>
                    <div class="controls">
                        <select id="type_[[day_position]]" class="type input-xxlarge">
                            <option value="Working day">Working day</option>
                            <option value="Day off">Day off</option>
                            <option value="Holiday">Holiday</option>
                            <option value="Trip">Trip</option>
		                    </select>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="title_[[day_position]]">Title</label>
                    <div class="controls">
                        <input type="text" id="title_[[day_position]]" class="title input-xxlarge">
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="desc_[[day_position]]">Description</label>
                    <div class="controls">
                        <textarea id="desc_[[day_position]]" class="desc input-xxlarge" rows="5"></textarea>
                    </div>
                </div>

                <center><button class="btn btn-success btn-large export-action">
                    Final step! <i class="icon-white icon-forward"></i> </button></center>
						</form>
		      </div>
      </div>
	</script>
{{/into}}
{{into slot="js_include"}}
  <script src="/lib/Importer.js"></script>
	<script src="/lib/vendor/jquery.scrollTo-1.4.3.1-min.js"></script>
{{/into}}
{{into slot="js_ready"}}
    hash = window.location.hash.substr(14);
    $(document).ready(function () {
        if (window.location.hash.length < 2) {
            $('a.btn').show();
        }
        else {
            Importer.$days = $('.days');
            Importer.$progress = $('.progress');
            Importer.import(hash);
        }
    });
{{/into}}
{{/wrap}}
