{{wrap with="layout.phtml"}}
  {{into slot="js_include"}}
    <script src="/lib/Instagram.js"></script>
    <script src="/app/import.js"></script>
  {{/into}}
  {{into slot="templates"}}
    <script id="template_step1" type="text/x-handlebars-template">
      <a class="btn btn-danger btn-large">
        Step 1/3. Connect your account <i class="icon-white icon-forward"></i>
      </a>
    </script>

    <script id="template_step2" type="text/x-handlebars-template">
      <ul class="import_days unstyled"></ul>
      <button class="btn btn-block btn-large paginate" style="margin: 10px 0; display: none;">Load more</button>
    </script>

    <script id="template_import_day" type="text/x-handlebars-template">
      <li class="day well">
        <ul class="thumbnails"></ul>
        <button class="btn btn-large btn-success analyze-action">
          Step 2/3. Analyze photos
          <i class="icon-white icon-forward"></i>
        </button>
      </li>
    </script>

    <script id="template_import_moment" type="text/x-handlebars-template">
      <li class="inline" style="display:none">
        <div class="thumbnail selected">
          <div class="img-wrap img-rounded">
            <img src="[[image]]" class="img-rounded" alt="[[title]]" />
            <span class="bage-bottom-right"><i class="icon-ok-sign"></i></span>
          </div>
        </div>
      </li>
    </script>

    <script id="template_step3" type="text/x-handlebars-template">
      <form class="form-horizontal" style="display:none">
        <div class="control-group">
          <label class="control-label">Title</label>
          <div class="controls">
            <input type="text" class="title input-xxlarge" value="[[title]]">
          </div>
        </div>

        <div class="control-group">
          <label class="control-label">Day type</label>
          <div class="controls">
            <select class="type input-xxlarge">
              <option value="Working day"[[#if-eq type "Working day"]] selected[[/if-eq]]>Working day</option>
              <option value="Day off"[[#if-eq type "Day off"]] selected[[/if-eq]]>Day off</option>
              <option value="Holiday"[[#if-eq type "Holiday"]] selected[[/if-eq]]>Holiday</option>
              <option value="Trip"[[#if-eq type "Trip"]] selected[[/if-eq]]>Trip</option>
            </select>
          </div>
        </div>

        <div class="control-group">
          <label class="control-label">Description</label>
          <div class="controls">
            <textarea class="description input-xxlarge" rows="5">[[description]]</textarea>
          </div>
        </div>

        <div class="text-center">
          <button class="btn btn-success btn-large export-action">
            Step 3/3. Save day
            <i class="icon-white icon-forward"></i>
          </button>
        </div>
      </form>
    </script>

    <script id="template_step4" type="text/x-handlebars-template">
      <div class="alert alert-success">
        Day successfully imported. Show <a href="/pages/[[id]]/day">result</a>.
      </div>
    </script>
  {{/into}}
  {{into slot="content"}}
    <div>
        <h1>Import from Instagram</h1>

        <div id="error_container" class="well cant alert alert-danger" style="display:none; margin-top:20px;">Sorry. You have no days with 3 or more photos.</div>

        <!--<div class="alert alert-info row" style="margin-top:20px;">
            Import from custom instagram account (debug only):
            <form class="form-inline custom-import-action">
                <input type="text" class="input-medium" placeholder="username">
                <input class="btn btn-info" type="submit" value="Import" />
            </form>
        </div>-->

        <div class="progress row" style="margin-top:20px;">
            <div class="bar bar-success" style="width: 0%;"></div>
        </div>

        <div id="step_container" class="row" style="text-align:center; margin-top: 20px;">
          <a class="btn btn-danger btn-large">
              Step 1 of 3. Authorization <i class="icon-white icon-forward"></i>
          </a>
        </div>
    </div>
  {{/into}}
{{/wrap}}
