<?
$this->menu = '';
?>
{{wrap with="layout.phtml"}}
{{into slot="js_include"}}
<link href="/styles/vendor/fuelux.css" rel="stylesheet">
<link href="/styles/vendor/fuelux-responsive.css" rel="stylesheet">
<script src="/lib/vendor/fuelux-wizard.js"></script>
<script src="/lib/Importer.js"></script>
{{/into}}
{{into slot="content"}}
<div class="fuelux">
	<div id="wizard" class="wizard">
		<ul class="steps">
			<li data-target="#step1" class="active"><span class="badge badge-info">1</span>Sign up<span class="chevron"></span></li>
			<li data-target="#step2"><span class="badge">2</span>Instagram<span class="chevron"></span></li>
			<li data-target="#step3"><span class="badge">3</span>Flickr<span class="chevron"></span></li>
			<li data-target="#step4"><span class="badge">4</span>Select a day<span class="chevron"></span></li>
			<li data-target="#step5"><span class="badge">5</span>Publish<span class="chevron"></span></li>
		</ul>
	</div>
	<br class="clearFix"/>
	<center>
	<div class="step-content">
		<div class="step-pane active" id="step1">
				<button class="btn btn-large facebook-action">
					<i class="icon icon-facebook-sign"/></i>
					&nbsp;Login with facebook
				</button>
			<script>
				$('.facebook-action').click(function(e) {
					$(this).off('click').html('<i class="icon-large icon-refresh icon-spin"></i> Login with Facebook');
					API.login(function() {
						$('#wizard').wizard('next', 'foo');
					});
				});
			</script>
		</div>
		<div class="step-pane" id="step2">
			<button class="btn btn-large instagram-action">
				<img src="http://instagram.com/favicon.ico"/>
				&nbsp;Connect to instagram
			</button>
			<button class="btn disabled skip-action">
				Skip&nbsp;<i class="icon icon-arrow-right"/></i>
			</button>
			<script>
				$('.instagram-action').click(function(e) {
					var importer = new Importer('instagram');
					if(!importer.isConnected()) {
						importer.login(function() {
							$('#wizard').wizard('next', 'foo');
						});
					}
					else
						$('#wizard').wizard('next', 'foo');
				});
			</script>
		</div>
		<div class="step-pane" id="step3">
			<button class="btn disabled back-action">
				<i class="icon icon-arrow-left"/></i>
				&nbsp;Back
			</button>
			<button class="btn btn-large flickr-action">
				<img src="http://l.yimg.com/g/favicon.ico" width="16"/>
				&nbsp;Connect to Flickr
			</button>
			<button class="btn disabled skip-action">
				Skip&nbsp;<i class="icon icon-arrow-right"/></i>
			</button>
			<script>
				$('.flickr-action').click(function(e) {
					var importer = new Importer('flickr');
					if(!importer.isConnected()) {
						importer.login(function() {
							$('#wizard').wizard('next', 'foo');
						});
					}
					else
						$('#wizard').wizard('next', 'foo');
				});
			</script>
		</div>
		<div class="step-pane" id="step4">
			<button class="btn disabled back-action">
				<i class="icon icon-arrow-left"/></i>
				&nbsp;Back
			</button>
			<button class="btn btn-large">
				<i class="icon icon-facebook-sign"/></i>
				&nbsp;Select
			</button>
		</div>
		<div class="step-pane" id="step5">
			<button class="btn disabled back-action">
				<i class="icon icon-arrow-left"/></i>
				&nbsp;Back
			</button>
			<button class="btn btn-large">
				<i class="icon icon-facebook-sign"/></i>
				&nbsp;Publish
			</button>
		</div>
	</div>
		</center>
{{/into}}
{{into slot="js_ready"}}
	$('#wizard').wizard();

	$('#wizard').on('stepclick', function(e, data) {
		console.log('step' + data.step + ' clicked');
		return e.preventDefault();
	});

	$('.back-action').click(function(e) {
		$('#wizard').wizard('previous');
	});

	$('.skip-action').click(function(e) {
		$('#wizard').wizard('next', 'foo');
	});


	{{/into}}
{{/wrap}}