<?
$this->title = 'Journal';
$this->menu = 'create_day';
?>
{{wrap with="layout.phtml"}}
	{{into slot="content"}}
		<h2><span class="muted">Today</span></h2>
		<div>
			<a href="/" class="pull-left" style="margin-right:20px;padding-bottom: 20px">
				<img src="http://onedayofmine.s3.amazonaws.com/days/7c325799164f92668b4090a6f970f47b2da9461b_266.jpeg"/>
			</a>
			<div>
				<h3><a href="/">Один день эрготерапевта</a></h3>
				<p>Всем привет! Меня зовут Женя, мне 33, я живу и работаю в Мюнхене, в Баварии. Вообще-то я еще не совсем
					эрготерапевт — я практикантка, и диплом у меня будет только через год. Но все равно я уже работаю по
					специальности. О том, кто такой эрготерапевт и что он делает, я написала здесь. А теперь, кому интересно
					— добро пожаловать в Мой День! Под катом ровно 54 фотографии про 24 апреля этого года.</p>
			</div>
			<ul class="inline">
				<li>
					<img style="width:124px" src="http://onedayofmine.s3.amazonaws.com/days/7c325799164f92668b4090a6f970f47b2da9461b_266.jpeg"/>
				</li>
				<li>
					<img style="width:124px" src="http://onedayofmine.s3.amazonaws.com/days/7c325799164f92668b4090a6f970f47b2da9461b_266.jpeg"/>
				</li>
				<li>
					<img style="width:124px" src="http://onedayofmine.s3.amazonaws.com/days/7c325799164f92668b4090a6f970f47b2da9461b_266.jpeg"/>
				</li>
				<li>
					<img style="width:124px" src="http://onedayofmine.s3.amazonaws.com/days/7c325799164f92668b4090a6f970f47b2da9461b_266.jpeg"/>
				</li>
			</ul>
		</div>
		<br style="clear:both"/>

	<div class="row-fluid">
	<h2><span class="muted">Journal</span></h2>
	<ul class="items-list">
		<li class="medium-item">
			<a href="#" >
				<img class="pull-left" src="http://onedayofmine.s3.amazonaws.com/days/87/89a921b4f5f0b484c0c7175edfab5b935fc4fbef_266.jpeg">
			</a>
			<ul class="inline">
				<li class="muted"><i class="icon icon-eye-open"></i>&nbsp;322</li>
				<li class="muted"><i class="icon icon-heart"></i>&nbsp;12</li>
				<li class="muted"><i class="icon icon-comments"></i>&nbsp;7</li>
			</ul>
			<a href="#"><h4>(1) Один день новосибирцев в Екатеринбурге</h4></a>
			<p>Всем здравствуйте! Меня зовут Саша, мне 26, работаю пиарщиком в строительной компании. Родилась я в городе
				Братске, живу в Новосибирске, а рассказывать буду о Екатеринбурге, где провела часть майских праздников в
				отличной компании.</p>
		</li>
		<li class="medium-item">
			<a href="#" >
				<img src="http://onedayofmine.s3.amazonaws.com/days/222551127fab79817037e872306c3d81cc8e67e5_266.jpeg" alt="" class="pull-left">
			</a>
			<ul class="inline">
				<li class="muted"><i class="icon icon-eye-open"></i>&nbsp;322</li>
				<li class="muted"><i class="icon icon-heart"></i>&nbsp;12</li>
				<li class="muted"><i class="icon icon-comments"></i>&nbsp;7</li>
			</ul>
			<a href="#"><h4 style="font-family: 'Ubuntu Mono', sans-serif;">(2) Один будний день рукодельницы</h4></a>
			<p>Всем привет! Зовут меня Екатериной, я живу в Ростове-на-Дону, занимаюсь скрапбукингом, мне недавно стукнуло 27 :) Мой день прошел в трудах дома. Получилось много фотографий еды, рукотворческого процесса, нашего жилища, захватились кусочки весеннего Ростова с его синим небом и яркой сочной зеленью.</p>
		</li>
		<li class="medium-item">
			<div style="border:1px solid #999;padding:10px;">
			<center>
			<h4>Facebook</h4>
			<div class="fb-like-box" data-href="https://www.facebook.com/Onedayofmine" data-width="240" data-height="230"
				     data-show-faces="true" data-stream="false" data-show-border="false" data-header="false">
			</div>
			<br/><br/>
			<h4>VKontakte</h4>
			<script type="text/javascript" src="//vk.com/js/api/openapi.js?96"></script>
			<div id="vk_groups"></div>
			<script type="text/javascript">
				VK.Widgets.Group("vk_groups", {mode: 0, width: "240", height: "150"}, 53796872);
			</script>
			</center>
			</div>
		</li>
		<li class="medium-item">
			<a href="#" >
				<img src="http://onedayofmine.s3.amazonaws.com/days/84/c007f801119f05917a1fc596c34e7f0b28c7863e_266.jpeg" alt="" class="pull-left">
			</a>
			<ul class="inline">
				<li class="muted"><i class="icon icon-eye-open"></i>&nbsp;322</li>
				<li class="muted"><i class="icon icon-heart"></i>&nbsp;12</li>
				<li class="muted"><i class="icon icon-comments"></i>&nbsp;7</li>
			</ul>
			<a href="#"><h4 style="font-family: 'PT Sans', sans-serif;">(4) Один день бегущего повара</h4></a>
			<p>Привет Всем! Меня зовут Макс или Running Chef, т.е. Бегущий Повар, потому что я люблю бег и по профессии я повар. Живу в Праге со своей семьей, работаю в пятизвездочном отеле в центре города и много занимаюсь спортом. Сегодня я покажу Вам один день из моей жизни, а именно 12 мая 2013 года.</p>
		</li>


		<li class="medium-item">
			<a href="#" >
				<img class="pull-left" src="http://onedayofmine.s3.amazonaws.com/days/87/89a921b4f5f0b484c0c7175edfab5b935fc4fbef_266.jpeg">
			</a>
			<ul class="inline">
				<li class="muted"><i class="icon icon-eye-open"></i>&nbsp;322</li>
				<li class="muted"><i class="icon icon-heart"></i>&nbsp;12</li>
				<li class="muted"><i class="icon icon-comments"></i>&nbsp;7</li>
			</ul>
			<a href="#"><h4 style="font-family: 'Andika', sans-serif;">(5) Один день новосибирцев в Екатеринбурге</h4></a>
			<p>Всем здравствуйте! Меня зовут Саша, мне 26, работаю пиарщиком в строительной компании. Родилась я в городе
				Братске, живу в Новосибирске, а рассказывать буду о Екатеринбурге, где провела часть майских праздников в
				отличной компании.</p>
		</li>
		<li class="medium-item">
			<a href="#" >
				<img src="http://onedayofmine.s3.amazonaws.com/days/222551127fab79817037e872306c3d81cc8e67e5_266.jpeg" alt="" class="pull-left">
			</a>
			<ul class="inline">
				<li class="muted"><i class="icon icon-eye-open"></i>&nbsp;322</li>
				<li class="muted"><i class="icon icon-heart"></i>&nbsp;12</li>
				<li class="muted"><i class="icon icon-comments"></i>&nbsp;7</li>
			</ul>
			<a href="#"><h4 style="font-family: 'Istok Web', sans-serif;">(6) Один будний день рукодельницы</h4></a>
			<p>Всем привет! Зовут меня Екатериной, я живу в Ростове-на-Дону, занимаюсь скрапбукингом, мне недавно стукнуло 27 :) Мой день прошел в трудах дома. Получилось много фотографий еды, рукотворческого процесса, нашего жилища, захватились кусочки весеннего Ростова с его синим небом и яркой сочной зеленью.</p>
		</li>
		<li class="medium-item">
			<a href="#" >
				<img src="http://onedayofmine.s3.amazonaws.com/days/38b783bf023633318f65e8fb065c4e577eeae060_266.jpeg" alt="" class="pull-left">
			</a>
			<ul class="inline">
				<li class="muted"><i class="icon icon-eye-open"></i>&nbsp;322</li>
				<li class="muted"><i class="icon icon-heart"></i>&nbsp;12</li>
				<li class="muted"><i class="icon icon-comments"></i>&nbsp;7</li>
			</ul>
			<a href="#"><h4 style="font-family: 'Ubuntu', sans-serif;">(7) Один день в корейском детском саду</h4></a>
			<p>Меня зовут Евгения. Вместе с мужем Тэгю и двумя детками я живу в Южной Корее. Сегодняшний мой рассказ о нашем семейном детсадовском дне. Такой день мы пережили впервые! Место действия: Южная Корея, провинция Кёнги-до, 27 апреля 2013 года.</p>
		</li>
		<li class="medium-item">
			<a href="#" >
				<img src="http://onedayofmine.s3.amazonaws.com/days/84/c007f801119f05917a1fc596c34e7f0b28c7863e_266.jpeg" alt="" class="pull-left">
			</a>
			<ul class="inline">
				<li class="muted"><i class="icon icon-eye-open"></i>&nbsp;322</li>
				<li class="muted"><i class="icon icon-heart"></i>&nbsp;12</li>
				<li class="muted"><i class="icon icon-comments"></i>&nbsp;7</li>
			</ul>
			<a href="#"><h4 style="font-family: 'PT Serif Caption', sans-serif;">(8) Один день бегущего повара</h4></a>
			<p>Привет Всем! Меня зовут Макс или Running Chef, т.е. Бегущий Повар, потому что я люблю бег и по профессии я повар. Живу в Праге со своей семьей, работаю в пятизвездочном отеле в центре города и много занимаюсь спортом. Сегодня я покажу Вам один день из моей жизни, а именно 12 мая 2013 года.</p>
		</li>


		<li class="medium-item">
			<a href="#" >
				<img class="pull-left" src="http://onedayofmine.s3.amazonaws.com/days/87/89a921b4f5f0b484c0c7175edfab5b935fc4fbef_266.jpeg">
			</a>
			<ul class="inline">
				<li class="muted"><i class="icon icon-eye-open"></i>&nbsp;322</li>
				<li class="muted"><i class="icon icon-heart"></i>&nbsp;12</li>
				<li class="muted"><i class="icon icon-comments"></i>&nbsp;7</li>
			</ul>
			<a href="#"><h4 style="font-family: 'PT Sans Caption', sans-serif;">(9) Один день новосибирцев в Екатеринбурге</h4></a>
			<p>Всем здравствуйте! Меня зовут Саша, мне 26, работаю пиарщиком в строительной компании. Родилась я в городе
				Братске, живу в Новосибирске, а рассказывать буду о Екатеринбурге, где провела часть майских праздников в
				отличной компании.</p>
		</li>
	</ul>
</div>

<div class="row-fluid">
	<h2><a href="#"><span class="muted">Ваши дни:</span></a></h2>
	<ul class="items-list">
		<li class="small-item">
			<a href="#" >
				<img src="http://onedayofmine.s3.amazonaws.com/days/b2595559904c83427d6d87455f82b9fdf4ed395a_266.jpeg">
			</a>
			<h5>Один день в трех странах</h5>
			<small>
			<ul class="inline">
				<li class="muted"><i class="icon icon-eye-open"></i>&nbsp;322</li>
				<li class="muted"><i class="icon icon-heart"></i>&nbsp;12</li>
				<li class="muted"><i class="icon icon-comments"></i>&nbsp;7</li>
			</ul>
			</small>
		</li>
		<li class="small-item">
			<a href="#" >
				<img src="http://onedayofmine.s3.amazonaws.com/days/73/8577e2d7e8b78291eb0f0d3996323877aba3e558_266.jpeg">
			</a>
			<h5>Станция Московского метрополитена «Пятницкое шоссе»</h5>
		</li>
		<li class="small-item">
			<a href="#" >
				<img src="http://onedayofmine.s3.amazonaws.com/days/87/89a921b4f5f0b484c0c7175edfab5b935fc4fbef_266.jpeg" alt="" class="pull-left">
			</a>
			<h5>Один день новосибирцев в Екатеринбурге</h5>
		</li>
		<li class="small-item">
			<a href="#" >
				<img src="http://onedayofmine.s3.amazonaws.com/days/87/89a921b4f5f0b484c0c7175edfab5b935fc4fbef_266.jpeg" alt="" class="pull-left">
			</a>
			<h5>Один день новосибирцев в Екатеринбурге</h5>
		</li>
		<li class="small-item">
			<a href="#" >
				<img src="http://onedayofmine.s3.amazonaws.com/days/87/89a921b4f5f0b484c0c7175edfab5b935fc4fbef_266.jpeg" alt="" class="pull-left">
			</a>
			<h5>Один день новосибирцев в Екатеринбурге</h5>
		</li>
		<li class="small-item">
			<a href="#" >
				<img src="http://onedayofmine.s3.amazonaws.com/days/87/89a921b4f5f0b484c0c7175edfab5b935fc4fbef_266.jpeg" alt="" class="pull-left">
			</a>
			<h5>Один день новосибирцев в Екатеринбурге</h5>
		</li>
		<li class="small-item">
			<a href="#" >
				<img src="http://onedayofmine.s3.amazonaws.com/days/87/89a921b4f5f0b484c0c7175edfab5b935fc4fbef_266.jpeg" alt="" class="pull-left">
			</a>
			<h5>Один день новосибирцев в Екатеринбурге</h5>
		</li>
		<li class="small-item">
			<a href="#" >
				<img src="http://onedayofmine.s3.amazonaws.com/days/87/89a921b4f5f0b484c0c7175edfab5b935fc4fbef_266.jpeg" alt="" class="pull-left">
			</a>
			<h5>Один день новосибирцев в Екатеринбурге</h5>
		</li>
		<li class="small-item">
			<a href="#" >
				<img src="http://onedayofmine.s3.amazonaws.com/days/b2595559904c83427d6d87455f82b9fdf4ed395a_266.jpeg">
			</a>
			<h5>Один день в трех странах</h5>
		</li>
		<li class="small-item">
			<a href="#" >
				<img src="http://onedayofmine.s3.amazonaws.com/days/73/8577e2d7e8b78291eb0f0d3996323877aba3e558_266.jpeg">
			</a>
			<h5>Станция Московского метрополитена «Пятницкое шоссе»</h5>
		</li>
		<li class="small-item">
			<a href="#" >
				<img src="http://onedayofmine.s3.amazonaws.com/days/87/89a921b4f5f0b484c0c7175edfab5b935fc4fbef_266.jpeg" alt="" class="pull-left">
			</a>
			<h5>Один день новосибирцев в Екатеринбурге</h5>
		</li>
		<li class="small-item">
			<a href="#" >
				<img src="http://onedayofmine.s3.amazonaws.com/days/87/89a921b4f5f0b484c0c7175edfab5b935fc4fbef_266.jpeg" alt="" class="pull-left">
			</a>
			<h5>Один день новосибирцев в Екатеринбурге</h5>
		</li>
	</ul>
</div>

<div class="row-fluid">
	<h2><a href="#"><span class="muted">Новые лица</span></a></h2>
	<ul class="items-list">
		<li class="user-item">
			<a href="#" >
				<img class="img-circle pull-left" src="http://onedayofmine.s3.amazonaws.com/355/058d06c2951fb38113f325ba4b3c2d52184ec8bb_192.jpeg">
			</a>
			<a href="#">
				<h5>Станислав Гималайскай</h5>
			</a>
			<p class="muted">
				<i class="icon icon-calendar"></i>&nbsp;2 <i class="icon icon-bookmark"></i>&nbsp;12 <i class="icon icon-envelope"></i>&nbsp;7
			</p>
			</center>
		</li>
		<li class="user-item">
			<a href="#" >
				<img class="img-circle pull-left" src="http://onedayofmine.s3.amazonaws.com/355/058d06c2951fb38113f325ba4b3c2d52184ec8bb_192.jpeg">
			</a>
			<a href="#">
				<h5>Станислав Гималайскай</h5>
			</a>
			<p class="muted">
				<i class="icon icon-calendar"></i>&nbsp;2 <i class="icon icon-bookmark"></i>&nbsp;12 <i class="icon icon-envelope"></i>&nbsp;7
			</p>
		</li>
		<li class="user-item">
			<a href="#" >
				<img class="img-circle pull-left" src="http://onedayofmine.s3.amazonaws.com/355/058d06c2951fb38113f325ba4b3c2d52184ec8bb_192.jpeg">
			</a>
			<a href="#">
				<h5>Станислав Гималайскай</h5>
			</a>
			<p class="muted">
				<i class="icon icon-calendar"></i>&nbsp;2 <i class="icon icon-bookmark"></i>&nbsp;12 <i class="icon icon-envelope"></i>&nbsp;7
			</p>
		</li>
		<li class="user-item">
			<a href="#" >
				<img class="img-circle pull-left" src="http://onedayofmine.s3.amazonaws.com/355/058d06c2951fb38113f325ba4b3c2d52184ec8bb_192.jpeg">
			</a>
			<a href="#">
				<h5>Станислав Гималайскай</h5>
			</a>
			<p class="muted">
				<i class="icon icon-calendar"></i>&nbsp;2 <i class="icon icon-bookmark"></i>&nbsp;12 <i class="icon icon-envelope"></i>&nbsp;7
			</p>
		</li>
		<li class="user-item">
			<a href="#" >
				<img class="img-circle pull-left" src="http://onedayofmine.s3.amazonaws.com/355/058d06c2951fb38113f325ba4b3c2d52184ec8bb_192.jpeg">
			</a>
			<a href="#">
				<h5>Станислав Гималайскай</h5>
			</a>
			<p class="muted">
				<i class="icon icon-calendar"></i>&nbsp;2 <i class="icon icon-bookmark"></i>&nbsp;12 <i class="icon icon-envelope"></i>&nbsp;7
			</p>
		</li>
		<li class="user-item">
			<a href="#" >
				<img class="img-circle pull-left" src="http://onedayofmine.s3.amazonaws.com/355/058d06c2951fb38113f325ba4b3c2d52184ec8bb_192.jpeg">
			</a>
			<a href="#"><h5>Станислав Гималайскай</h5></a>
			<p class="muted">
				<i class="icon icon-calendar"></i>&nbsp;2 <i class="icon icon-bookmark"></i>&nbsp;12 <i class="icon icon-envelope"></i>&nbsp;7
			</p>
		</li>
	</ul>
</div>
{{/into}}
{{into slot="css"}}
h2 {

}
h5 {
	font-weight:normal;
}

.items-list .big-item, .items-list .comments-item  {
	width:552px;
}

.items-list .medium-item {
	width:267px;
}

.items-list .small-item,
.items-list .user-item {
  width:124px;
}

.items-list .user-item {
	text-align:center;
}

.comments-item ul.unstyled li {
  vertical-align:top;
}

.items-list {
	margin-left: 0;
	list-style: none;
}

.items-list > li {
	vertical-align:top;
	padding:0 20px 20px 0;
	display: inline-block;
	*display: inline;
	*zoom: 1;
}

.items-list .last-item {
	vertical-align:top;
	padding:0 0 16px 0;
}
{{/into}}
{{/wrap}}