<?
$this->title = lmb_i18n("Map");
$this->menu = 'map';
?>
{{wrap with="layout.phtml"}}
{{into slot="js_include"}}
<script src="//api-maps.yandex.ru/2.0/?load=package.standard,package.geoObjects,package.clusters&lang=ru-RU"
        type="text/javascript"></script>
<script type="text/javascript">

	var days = {$#days_json|raw};

	ymaps.ready(function ()
	{
		var user_coords = [ymaps.geolocation.latitude, ymaps.geolocation.longitude],
				map = new ymaps.Map("map", {
					center: user_coords,
					zoom: 2,
					behaviors: ['default', 'scrollZoom']
				}, {
					geoObjectClusterDisableClickZoom: true,
					minZoom: 2
				}),
				placemarks = [],
				clusterer = new ymaps.Clusterer({
					clusterBalloonContentBodyLayout: "cluster#balloonAccordionContent",
					clusterBalloonWidth: 500,
					clusterBalloonHeight: 250
				});
		map.controls.add('zoomControl', { left: 5, top: 5 });

		$.each(days, function(index, day)
		{
			placemarks[index] = new ymaps.Placemark(
					[day.location_lat, day.location_long],
					{
						clusterCaption: day.title,
						balloonContentHeader: day.title,
						balloonContentBody: getBody(day)
					}
			);
		});

		clusterer.add(placemarks);
		map.geoObjects.add(clusterer);

		function getBody(day)
		{
			var str = '<div class=map-entry>' +
			'<div class=author>' + day.date + '</div>';
			str += '<a href="/pages/' + day.id + '/day"><img src="' + day.image_266 + '" class="pull-left img-polaroid"/></a>';
			str += '<div>' + day.final_description.replace(/([^>])\n/g, '$1<br/><br/>') + '</div>' +
				'<br/><a href="/pages/' + day.id + '/day">Read more &rarr;</a>' +
			'</div>';
			return str;
		}
	});

</script>
{{/into}}

{{into slot="content"}}
<style>
	#map {
		width: 980px;
		height: 600px;
	}

	.map-entry {
		padding: 10px 20px 10px 15px;
	}

	.map-entry img {
		width:100px;
		height:100px;
		margin: 0 5px 5px 0;
	}

	.author {
		text-align: right;
		font-style: italic;
		font-size: .8em;
		line-height: .8em;
		margin-right: 5px;
		margin-bottom: 5px;
	}

	.ymaps-b-cluster-accordion__item-caption, .ymaps-b-cluster-accordion__item {
		font-family: "PT Serif", "Arial Narrow Bold", sans-serif;
		font-size: 15px;
	}

	.ymaps-b-cluster-accordion__item-caption {
		color: #777777;
		text-decoration: none;
	}
</style>
<div class="row-fluid">
	<center>
		<div id="map"></div>
	</center>
</div>
{{/into}}
{{/wrap}}
