<? $this->title = $this->moment->getDay()->title; ?>
{{wrap with="layout.phtml"}}
{{into slot="meta"}}
  <meta property="og:type"   content="{$#facebook_app_namespace}:moment" />
  <meta property="og:url"    content="{$#host_url}pages/{$#moment.id}/moment" />
  <meta property="og:title"  content="{$#moment.description}" />
  <meta property="og:description"  content="{$#moment.description}" />
  <meta property="og:image"  content="<?= lmbToolkit::instance()->getStaticUrl($this->moment->getImage()); ?>" />
  <meta property="{$#facebook_app_namespace}:day" content="<?= $this->moment->getDay()->facebook_id; ?>" />
  {{/into}}
  {{into slot="content"}}
<h1>Moment #{$#moment.id}</h1>
{{/into}}
  {{/wrap}}
