<?
$this->title = "My followers and following";
$this->menu = 'me';
?>
{{wrap with="layout.phtml"}}
  {{into slot="js_ready"}}
    function attachFollowingListeners(container) {
      container.find('.follow-action').click(function() {
        var user_id = $(this).data('user-id');
        $(this).addClass('hide');
        $(this).parent().find('.unfollow-action').removeClass('hide');
        API.post('users/' + user_id + '/follow').send();
      });

      container.find('.unfollow-action').click(function() {
        var user_id = $(this).data('user-id');
        $(this).addClass('hide');
        $(this).parent().find('.follow-action').removeClass('hide');
        API.post('users/' + user_id + '/unfollow').send();
      });
    }

    attachFollowingListeners($('.user-relations'));
  {{/into}}
  {{into slot="content"}}
    <div class="row-fluid user-relations">
      <div class="span6">
        <h1>Followers <small><?= count($this->followers); ?></small></h1>
        {{apply template="users_list" users="{$#followers}"/}}
      </div>
      <div class="span6">
        <h1>Following <small><?= count($this->following); ?></small></h1>
        {{apply template="users_list" users="{$#following}"/}}
      </div>
    </div>
  {{/into}}
{{/wrap}}
