<?
$this->title = "My followers and following";
$this->menu = 'me';
?>
{{wrap with="layout.phtml"}}
{{into slot="content"}}
<div class="row">
    <div class="span6">
		    <h1>Followers <small>3 people</small></h1>
		    <ul class="unstyled" style="margin-top:1em">
				    <li style="background-color:#eeeeee">
						    <div class="row" >
								    <div class="span1">
										    <img src="http://images.instagram.com/profiles/profile_1450621_75sq_1360187746.jpg"/>
								    </div>
		                <div class="span5">
				                <a href="">Name</a> - occupation from location
				                <small>asdasdas</small>
                        <div class="pull-right" style="height:70px;">
                            <a href="#" class="btn" style="margin:17px 10px 0 0">Follow</a>
                        </div>
		                </div>
                </div>
				    </li>
		    </ul>
    </div>
    <div class="span6">
        <h1>Following</h1>
        <ul class="unstyled"  style="margin-top:1em">
            <li style="background-color:#eeeeee">
                <div class="row" >
                    <div class="span1">
                        <img src="http://images.instagram.com/profiles/profile_1450621_75sq_1360187746.jpg"/>
                    </div>
                    <div class="span5">
                        <a href="">Name</a> - occupation from location
                        <small>asdasdas</small>
                        <div class="pull-right" style="height:70px;">
                            <a href="#" class="btn btn-danger" style="margin:17px 10px 0 0">Unfollow</a>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>

{{/into}}
{{/wrap}}
