<?
$this->title = "Profile";
$this->menu = 'me';
?>
{{wrap with="layout.phtml"}}
{{into slot="content"}}
<div class="row">
	<div class="span2"><h1>Profile</h1></div>
	<div class="span5"></div>
	<div class="span3"><h3>Connected accounts:</h3></div>
</div>
<div class="row">
	<div class="span2">
		<div style="width:192px;margin:0 auto;background-color:#fff">
			<img class="change_photo" src="{$#current_user.image_192}"/>
			<small>Tap photo if you want</small>
		</div>
	</div>
	<div class="span5">
		<form class="form-horizontal">
			<div class="control-group">
				<label class="control-label" for="inputName">Name</label>

				<div class="controls">
					<input type="text" id="inputName" placeholder="Name" value="{$#current_user.name}">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="inputOccupation">Occupation</label>

				<div class="controls">
					<input type="text" id="inputOccupation" placeholder="Occupation" value="{$#current_user.occupation}">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="inputLocation">Location</label>

				<div class="controls">
					<input type="text" id="inputLocation" placeholder="location" value="{$#current_user.location}">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="inputBirthday">Birthday</label>
				<div class="controls">
					<input id="inputBirthday" type="date" placeholder="dd/mm/yyyy" value="{$#current_user.birthday}">
				</div>
			</div>

			<div class="control-group">
				<div class="controls">
					<div class="alert alert-success hide">
						Profile saved!
					</div>
				</div>
			</div>
			<div class="control-group">
				<div class="controls">
					<button type="submit" class="btn btn-large btn-success update-action">
						<i class="icon icon-ok"></i> Update
					</button>
				</div>
			</div>
		</form>
	</div>
	<div class="span3">
		<button type="submit" class="btn <?= $this->current_user['instagram_connected'] ? 'btn-danger' : '' ?> btn-large instagram-action">
			<i class="icon icon-sign<?= $this->current_user['instagram_connected'] ? 'out' : 'in' ?>"></i> Instagram
		</button>

		<br/><br/>
		<button type="submit" class="btn <?= $this->current_user['flickr_connected'] ? 'btn-danger' : '' ?> btn-large flickr-action">
			<i class="icon icon-sign<?= $this->current_user['flickr_connected'] ? 'out' : 'in' ?>"></i> Flickr
		</button>
	</div>
</div>
{{/into}}
{{into slot="js_ready"}}
	$('.update-action').click(function(event) {
		var data = {
			name: $('#inputName').val(),
			location: $('#inputLocation').val(),
			occupation: $('#inputOccupation').val(),
			birthday: $('#inputBirthday').val(),
		};
		var req = API.request('POST', 'my/profile', data).complete(function() {
			$('.alert-success').show();
		}).send();
		return false;
	});

	$('.instagram-action').click(function() {
		if($(this).hasClass('btn-danger'))
		{
			if(!confirm("Are you sure want to remove Instagram connection?"))
				return;
			$(this).removeClass('btn-danger').removeAttr('disabled');
			$(this).find('i').removeClass('icon-signout').addClass('icon-signin');
			var req = API.post('instagram/logout').send();
		}
		else
		{
			alert('Здесь будет привязка аккаунта');
		}
	});

	$('.flickr-action').click(function() {
		if($(this).hasClass('btn-danger'))
		{
			if(!confirm("Are you sure want to remove Flickr connection?"))
			return;
			$(this).removeClass('btn-danger').removeAttr('disabled');
			$(this).find('i').removeClass('icon-signout').addClass('icon-signin');
			var req = API.post('flickr/logout').send();
		}
		else
		{
			alert('Здесь будет привязка аккаунта');
		}
	});
{{/into}}
{{/wrap}}
