<?
$this->title = "Profile";
$this->menu = 'me';
?>
{{wrap with="layout.phtml"}}
{{into slot="content"}}
<h1>Profile</h1>
<div>
		<div style="" class="pull-left">
		    <div style="width:192px;margin:0 auto;background-color:#fff">
		        <img class="change_photo" src="{$#current_user.image_192}"/>
		        <small>Tap photo if you want</small>
		    </div>
		</div>
		<div class="pull-left">
        <form class="form-horizontal">
            <div class="control-group">
                <label class="control-label" for="inputName">Name</label>
                <div class="controls">
                    <input type="text" id="inputName" placeholder="Name" value="{$#current_user.name}">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="inputOccupation">Occupation</label>
                <div class="controls">
                    <input type="text" id="inputOccupation" placeholder="Occupation" value="{$#current_user.occupation}">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="inputLocation">Location</label>
                <div class="controls">
                    <input type="text" id="inputLocation" placeholder="location" value="{$#current_user.location}">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="inputBirthday">Birthday</label>
                <div class="controls">
                    <input id="inputBirthday" type="date" placeholder="dd/mm/yyyy" value="{$#current_user.birthday}">
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <div class="alert alert-success hide">
		                    Profile saved!
                    </div>
                </div>
	          </div>
            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn btn-success update-action">
		                    <i class="icon icon-ok"></i> Update
                    </button>
                </div>
            </div>
        </form>
		</div>
	</div>
{{/into}}
{{into slot="js_ready"}}
		$('.update-action').click(function(event) {
				var data = {
					name: $('#inputName').val(),
					location: $('#inputLocation').val(),
					occupation: $('#inputOccupation').val(),
					birthday: $('#inputBirthday').val(),
				};
				var req = API.request('POST', 'my/profile', data).complete(function() {
					$('.alert-success').show();
				}).send();
				return false;
		});
{{/into}}
{{/wrap}}
