{{wrap with="layout.phtml"}}
{{into slot="content"}}
<div>
	<div class="row">
		<div class="span4">
			<h5>Instagram</h5>
			<button class="btn btn-info" id="login_i">login</button>
			<button class="btn" id="user_i">user</button>
			<button class="btn" id="photos_i">photos</button>
			<button class="btn" id="days_i">days</button>
			<button class="btn btn-danger" id="logout_i">logout</button>
		</div>
		<div class="span4">
			<h5>Flickr</h5>
			<button class="btn btn-info" id="login">login</button>
			<button class="btn" id="user">user</button>
			<button class="btn" id="photos">photos</button>
			<button class="btn" id="days">days</button>
			<button class="btn btn-danger" id="logout">logout</button>
		</div>
		<div class="span3">
			<h5>Facebook</h5>
			<button class="btn" id="user_f">user</button>
			<button class="btn" id="photos_f">photos</button>
			<button class="btn" id="days_f">days</button>
		</div>
	</div>

	<br/>
	<div class="row">
		<div class="span12" id="out"></div>
	</div>

{{/into}}
{{into slot="js_include"}}
<script src="/lib/Importer.js"></script>
{{/into}}
{{into slot="js_ready"}}

obj2string = function (obj) {
var t = typeof (obj);
if (t != "object" || obj === null) {
// simple data type
if (t == "string") obj = '"'+obj+'"';
return String(obj+'<br/>');
}
else {
// recurse array or object
var n, v, json = [], arr = (obj && obj.constructor == Array);
for (n in obj) {
v = obj[n]; t = typeof(v);
if (t == "string") v = '"'+v+'"';
else if (t == "object" && v !== null) v = obj2string(v);
json.push((arr ? "" : '"' + n + '":') + String(v) + "<br/>");
}
return (arr ? "[" : "{") + String(json) + (arr ? "]" : "}");
}
};

function addClick(selector, url) {
	$(selector).click(function(){
		$('#out').html(null);
		API.get(url).success(function(resp) {
			$('#out').html(obj2string(resp.data.result));
		}).send();
	});
}

	addClick('#login_i', 'instagram/login_url');
	addClick('#user_i', 'instagram/user');
	addClick('#photos_i', 'instagram/photos');
	addClick('#days_i', 'instagram/days');
	addClick('#logout_i', 'instagram/logout');

	addClick('#login', 'flickr/login_url');
	addClick('#user', 'flickr/user');
	addClick('#photos', 'flickr/photos');
	addClick('#days', 'flickr/days');
	addClick('#logout', 'flickr/logout');

	addClick('#user_f', 'facebook/user');
	addClick('#photos_f', 'facebook/photos');
	addClick('#days_f', 'facebook/days');

{{/into}}
{{/wrap}}
