<?
$this->menu = '';
?>
{{wrap with="layout.phtml"}}
{{into slot="css"}}

{{/into}}
{{into slot="content"}}
<div>
	<br/>
	<div class="row">
		<div class="span2">
      <img src="{$#user.image_192}" class="pull-left"/>
		</div>
		<div class="span6">
      <h1>{$#user.name}</h1>
      <ul class="unstyled">
        <li><i class="icon icon-wrench"></i> occupation: {$#user.occupation}</li>
        <li><i class="icon icon-map-marker"></i> location: {$#user.location|default:"?"}</li>
        <li><i class="icon icon-hand-right"></i> followers: {$#user.followers_count}</li>
        <li><i class="icon icon-hand-left"></i> following: {$#user.following_count}</li>
      </ul>
		</div>
		<div class="span4">
      <div class="span4" style="margin-right:30px">
        <h3>Followers <small><?= count($this->user['followers']); ?> people</small></h3>
        {{apply template="users_list" users="{$#user.followers}"/}}
      </div>
      <div class="span4">
        <h3>Following <small><?= count($this->user['following']); ?> people</small></h3>
        {{apply template="users_list" users="{$#user.following}"/}}
      </div>
		</div>
	</div>
	<div class="row">
			<div class="span12">
          {{apply template="days_list" days="$#user.days"/}}
			</div>
	</div>

</div>
{{/into}}
{{/wrap}}
