<div class='tabs'>

  <ul>
    <li id='properties'><a>Свойства</a></li>
  </ul>

  <div id="tab_properties">


        <dl class="field">
          <dt>{{label for="facebook_uid"}}facebook_uid:{{/label}}</dt>
          <dd>{{input id="facebook_uid" name="facebook_uid" type="text" title="facebook_uid"/}}</dd>
        </dl>

        <dl class="field">
          <dt>{{label for="cip"}}cip:{{/label}}</dt>
          <dd>{{input id="cip" name="cip" type="text" title="cip"/}}</dd>
        </dl>


  </div>

</div>
