<div class='tabs'>

  <ul>
    <li id='properties'><a>Свойства</a></li>
  </ul>

  <div id="tab_properties">
    
      
        <dl class="field">
          <dt>{{label for="fb_uid"}}fb_uid:{{/label}}</dt>
          <dd>{{input id="fb_uid" name="fb_uid" type="text" title="fb_uid"/}}</dd>
        </dl>
      
        <dl class="field">
          <dt>{{label for="cip"}}cip:{{/label}}</dt>
          <dd>{{input id="cip" name="cip" type="text" title="cip"/}}</dd>
        </dl>
      
    
  </div>

</div>