<div class='tabs'>

  <ul>
    <li id='properties'><a>Свойства</a></li>
  </ul>

  <div id="tab_properties">
    
      
        <dl class="field">
          <dt>{{label for="text"}}text:{{/label}}</dt>
          <dd>{{textarea id="text" name="text" type="text" title="text" cols="40" rows="26"/}}</dd>
        </dl>
      
        <dl class="field">
          <dt>{{label for="cip"}}cip:{{/label}}</dt>
          <dd>{{input id="cip" name="cip" type="text" title="cip"/}}</dd>
        </dl>
      
    
  </div>

</div>