{{wrap with="front_page_layout.phtml" in="content_zone"}}
  <h1>MomentComment #{$this->item.id}</h1>
  <p><a href="/moment_comment/">к списку</a></p>
  <ul>
    <li>id: {$this->item.id}</li>
  
    <li>user_id: {$this->item.user_id}</li>
  
    <li>moment_id: {$this->item.moment_id}</li>
  
    <li>text: {$this->item.text}</li>
  
    <li>likes_count: {$this->item.likes_count}</li>
  
    <li>ctime: {$this->item.ctime}</li>
  
    <li>utime: {$this->item.utime}</li>
  
    <li>cip: {$this->item.cip}</li>
  </ul>
{{/wrap}}