{{wrap with="front_page_layout.phtml" in="content_zone"}}
  <h1>Complaint #{$this->item.id}</h1>
  <p><a href="/complaint/">к списку</a></p>
  <ul>
    <li>id: {$this->item.id}</li>
  
    <li>user_id: {$this->item.user_id}</li>
  
    <li>text: {$this->item.text}</li>
  
    <li>day_id: {$this->item.day_id}</li>
  
    <li>moment_id: {$this->item.moment_id}</li>
  
    <li>ctime: {$this->item.ctime}</li>
  
    <li>cip: {$this->item.cip}</li>
  </ul>
{{/wrap}}