{{template name='days_list'}}
		{{list using="$days"}}
				<ul class="days">
				    {{list:item}}
				    <li>
						    <dl class="with-box-shadow">
								    <dt>
                        <a href="/pages/{$item.id}/day">
                            <img src="{$item.image_532|default:'/img/no_photo.png'}" alt="{$item.final_description}">
                        </a>
									      <span class="day-controls-overlay-left">
												    <i class="icon icon-heart"></i> {$item.likes_count}
										    </span>
										    <span class="day-controls-overlay-right">
												    <i class="icon icon-large icon-comments"></i> {$item.comments_count}
										    </span>
								    </dt>
								    <dd>
                        <div>
                            <a href="/pages/{$item.id}/day">
		                            {$item.title|i18n_clip:25,0,"&hellip;"}
	                          </a>
	                          <br/>
		                        <a href="/pages/{$item.user.id}/user">
                                <small>{$item.user.name}</small>
                            </a>
                        </div>
								    </dd>
						    </dl>
				    </li>
				    {{/list:item}}
				</ul>
				{{list:default}}
						No days found
				{{/list:default}}
		{{/list}}
{{/template}}

<script id="days_list" type="text/x-handlebars-template">
		<ul class="days">
				[[#days]]
		    <li>
		        <dl class="with-box-shadow">
		            <dt>
		                <a href="/pages/[[id]]/day">
		                    <img src="[[image_532]]" alt="[[final_description]]">
		                </a>
		            </dt>
		            <dd>
		                <div>
		                    <a href="/pages/[[id]]/day">
		                        [[clip title 30]]
		                    </a>
		                    <br/>
		                    <a href="/pages/[[user.id]]/user">
		                        <small>[[user.name]]</small>
		                    </a>
		                </div>
		            </dd>
		        </dl>
		    </li>
        [[/days]]
		</ul>
</script>

{{template name='users_list'}}
		{{list using="$users"}}
		<div class="users">
		    {{list:item}}
		    <div class="row">
		        <div class="left">
		            <a href="/pages/{$item.id}/user">
		                <img src="{$item.image_72}"/>
		            </a>
		        </div>
		        <div class="middle">
		            <a href="/pages/{$item.id}/user">{$item.name}</a>
		            <br/>
		            <small>{$item.occupation} <? if($item['location']) { ?>{$item.location}<? } ?></small>
		        </div>
		        <div class="right">
		            <a href="#" user_id="{$item.id}" class="follow-action btn btn-info <? if($item['following']) { ?>hide<? } ?>">Follow</a>
		            <a href="#" user_id="{$item.id}" class="unfollow-action btn btn-danger <? if(!$item['following']) { ?>hide<? } ?>">Unfollow</a>
		        </div>
		    </div>
		    {{/list:item}}
		</div>
		{{/list}}
{{/template}}

<script id="users_list" type="text/x-handlebars-template">
    <ul class="unstyled">
        [[#users]]
        <li style="background-color:#eeeeee; margin-top:10px">
            <div class="row" >
                <div class="span1">
                    <img src="[[image]]"/>
                </div>
                <div class="span5">
                    <a href="">[[name]]</a>
                    <small>[[text]]</small>
                    <div class="pull-right" style="height:70px;">
                        <a href="#" class="btn [[btn_class]]" style="margin:17px 10px 0 0" [[btn_attr]]="[[btn_value]]">[[btn_text]]</a>
                    </div>
                </div>
            </div>
        </li>
        [[/users]]
    </ul>
</script>
