<?
$this->title = "OneDayOfMine";
$this->fb_disabled = true;
$this->menu_disabled = true;
?>
{{wrap with="layout.phtml"}}
{{into slot="meta"}}
<meta property="og:title" content="One Day of Mine - Live the life through other people's eyes"/>
<meta property="og:type" content="company"/>
<meta property="og:site_name" content="One Day of Mine - Live the life through other people's eyes"/>
<meta property="og:description" content="<ul>
	<li>new life for old photos</li>
	<li>easy to use: just click next and enjoy our magic</li>
	<li>look at life through the eyes of different people</li>
	<li>gain interest of other people by publishing days from your life</li>
</ul>"/>
<meta property="og:url" content="onedayofmine.com"/>
<meta property="og:image"
			content="https://launchrock-assets.s3.amazonaws.com/facebook-files/LEKBNZBC_1363177046270.png?_=0"/>
{{/into}}
{{into slot="content"}}
<div class="hero-unit">
	<div class="row">
		<div class="span6">
			<h1>One Day Of Mine</h1>
			<p class="lead">Live the life through other people's eyes</p>
			<ul class="unstyled">
				<li>
					<i class="icon-large icon-camera-retro"></i>
					new life for old photos
				</li>
				<li>
					<i class="icon-large icon-magic"></i>
					easy to use: just click next and enjoy our magic
				</li>
				<li>
					<i class="icon-large icon-eye-open"></i>
					look at life through the eyes of different people
				</li>
				<li>
					<i class="icon-large icon-group"></i>
					gain interest of other people by publishing days from your life
				</li>
				<li>
					<i class="icon-large icon-hand-right"></i>
					stay tuned
					<div id="lr-widget" rel="LEKBNZBC"></div>
					<script type="text/javascript" src="//ignition.launchrock.com/ignition-current.min.js"></script>
				</li>
				<li>
					<hr/>
					<i class="icon-large icon-question-sign"></i>
					Do you have any questions? <a href="mailto:welcome@onedayofmine.com">welcome@onedayofmine.com</a>!
				</li>
			</ul>
		</div>
		<div class="span4">
			<script src="http://widgets.twimg.com/j/2/widget.js"></script>
			<script>
				new TWTR.Widget({
					version: 2,
					type: 'user',
					search: '@OneDayOfMine',
					rpp: 5,
					interval: 6000,
					width:'100%',
					height: 350,
					footer: '',
					theme: {
						shell: {
							background: '#eee',
							color: '#000'
						},
						tweets: {
							background: '#eee',
							color: '#000',
							links: '#9c0000'
						}
					},
					features: {
						scrollbar: true,
						loop: false,
						live: false,
						hashtags: false,
						timestamp: false,
						avatars: true,
						behavior: 'all'
					}
				}).render().start();
			</script>
		</div>
		</div>
	</div>
	{{/into}}
	{{into slot="js_ready"}}
	{{/into}}
	{{/wrap}}
