<?
$this->title = "Live the life through other people's eyes";
$this->menu = 'journal';
?>

{{template name="big_day"}}
<? $additional_class = isset($additional_class) ? $additional_class : ''; ?>
<li class="big-day {$additional_class}">
	<? if(isset($title)) { ?>
		<h3 class="muted">
			{$title}
			<? if(isset($icon)) { ?>
				<i class="icon icon-{$icon}"></i>&nbsp;
			<? } ?>
		</h3>
	<? } ?>
	<a href="/pages/{$day.id}/day">
		<div class="img" style="background:url({$day.image_532}) no-repeat center center;"></div>
	</a>
  <a href="/pages/{$day.id}/day">
    <h4>{$day.title}</h4>
  </a>
	<p>{$day.final_description|nl2br}</p>
	<ul class="inline text-center pull-right">
		<li class="muted"><i class="icon icon-eye-open"></i>&nbsp;{$day.views_count}</li>
		<li class="muted"><i class="icon icon-heart"></i>&nbsp;{$day.likes_count}</li>
		<li class="muted"><i class="icon icon-comments"></i>&nbsp;{$day.comments_count}</li>
		<li class="muted">
			<i class="icon {$day.type|day_type_icon}"></i>
			&nbsp;{$day.type|lowercase|default:'working day'}
		</li>
	</ul>
</li>
{{/template}}

{{template name="medium_day"}}
	<? $additional_class = isset($additional_class) ? $additional_class : ''; ?>
	<li class="medium-day {$additional_class}">
		<? if(isset($title)) { ?>
			<h3 class="muted">
				{$title}&nbsp;
				<? if(isset($icon)) { ?>
					<i class="icon icon-{$icon}"></i>
				<? } ?>
			</h3>
		<? } ?>
		<a href="/pages/{$day.id}/day">
			<img src="{$day.image_266}">
		</a>
		<a href="/pages/{$day.id}/day">
			<h4>{$day.title|i18n_clip:30,0,"&hellip;"}</h4>
		</a>
		<p>{$day.final_description|nl2br|i18n_clip:350,0,"&hellip;"}</p>
		<ul class="inline pull-right">
			<li class="muted"><i class="icon icon-eye-open"></i>&nbsp;{$day.views_count}</li>
			<li class="muted"><i class="icon icon-heart"></i>&nbsp;{$day.likes_count}</li>
			<li class="muted"><i class="icon icon-comments"></i>&nbsp;{$day.comments_count}</li>
			<li class="muted">
				<i class="icon {$day.type|day_type_icon}"></i>
				&nbsp;{$day.type|lowercase|default:'working day'}
				</li>
		</ul>
	</li>
{{/template}}

{{template name="small_day"}}
	<? $additional_class = isset($additional_class) ? $additional_class : ''; ?>
	<li class="small-day {$additional_class}">
		<a href="/pages/{$day.id}/day">
			<img src="{$day.image_266}">
		</a>
		<a href="/pages/{$day.id}/day">
			<h5>{$day.title}</h5>
		</a>
		<small>
			<ul class="inline">
				<li class="muted"><i class="icon icon-eye-open"></i>&nbsp;{$day.views_count}</li>
				<li class="muted"><i class="icon icon-heart"></i>&nbsp;{$day.likes_count}</li>
				<li class="muted"><i class="icon icon-comments"></i>&nbsp;{$day.comments_count}</li>
				<li class="muted">
						<i class="icon {$day.type|day_type_icon}"></i>
						&nbsp;{$day.type|lowercase|default:'working day'}
				</li>
			</ul>
		</small>
	</li>
{{/template}}

{{wrap with="layout.phtml"}}
  <style>
  {{into slot="css"}}
		h4 {
			padding: 5px 0 10px 0;
		}

		.featured_day {
			position:relative;
			margin-bottom:40px;
		}

    #preview-list {
	    position:absolute;
	    width:701px;
	    bottom:0px;
	    left:276px;
	    margin:0;
	    height:133px;
	    white-space:nowrap;
    }

	  #preview-list li {
		  white-space: nowrap;
		  width:133px;
		  margin:0 6px 0 0;
	  }

    .big-item, .comments-item, .big-day  {
      width:532px;
    }

		.big-day {
			padding-bottom:40px;
		}

		.big-day div.img {
			width:532px;
			height:266px;
		}

    .medium-item, .medium-day {
      width:266px;
    }

		.medium-day {
			padding-bottom:30px;
		}

    .small-item, .user-item, .day-item {
      width:120px;
    }

		.user-item, .small-day {
			padding-bottom:20px;
		}

    .user-item {
      text-align:center;
    }

    .comments-item ul.unstyled li {
      vertical-align:top;
    }

    .items-list {
      margin-left: 0;
      list-style: none;
    }

    .items-list > li {
      vertical-align:top;
      display: inline-block;
      *display: inline;
			padding-top:0;
			padding-left:0;
      *zoom: 1;
    }

		.items-list .user-item {
			text-align:center;
		}

		.padded {
			padding-right:27px;
		}

    #preview-list li {
      padding-bottom: 0
    }

    .call-to-action {
      position: absolute;
      top: 40%;
      right: -46px;
      width: 40px;
      height: 40px;
      margin-top: -20px;
      font-size: 60px;
      font-weight: 100;
      line-height: 30px;
      color: #ffffff;
      text-align: center;
      background: #222222;
      border: 3px solid #ffffff;
      -webkit-border-radius: 23px;
      -moz-border-radius: 23px;
      border-radius: 23px;
      opacity: 0.5;
      filter: alpha(opacity=50);
      text-decoration: none !important;
    }
  {{/into}}
  </style>

  {{into slot="js_ready"}}
    var original_featured_img_src = '{$#featured_day.image_266|default:'/img/no_photo.png'}';
    var $featured_day_image_cover = $('#featured_day_image_cover');
    var $featured_day_image = $('#featured_day_image');
    $('#preview-list img').hover(
      //in
      function(event) {
        var $this = $(this);
        $featured_day_image_cover.stop(true, true).animate({opacity: 0}, 'fast', function() {
          $featured_day_image.attr('src', $this.attr('src'));
          $featured_day_image_cover.stop(true, true).animate({opacity: 1}, 'fast');
        });
      },
      //out
      function(event) {
        $featured_day_image_cover.stop(true, true).animate({opacity: 0}, 'fast', function() {
          $featured_day_image.attr('src', original_featured_img_src);
          $featured_day_image_cover.stop(true, true).animate({opacity: 1}, 'fast');
        });
      }
    );
  {{/into}}
  {{into slot="content"}}
    <?php if($this->featured_day) { ?>
      <h2><span class="muted">{{__ text="Featured"}}</span></h2>
      <div class="featured_day clearfix">
        <div id="featured_day_image_cover">
        	<a href="/pages/{$#featured_day->id}/day" class="pull-left" style="margin-right:10px;">
        		<img id="featured_day_image" src="{$#featured_day->image_266|default:'/img/no_photo.png'}" alt="{$#featured_day->final_description}" />
        	</a>
        </div>
      	<div>
      		<h3><a href="/pages/{$#featured_day->id}/day">{$#featured_day->title|i18n_clip:40,0,"&hellip;"}</a></h3>
      		<p style="height:94px;overflow: hidden">
            {$#featured_day->final_description|nl2br|i18n_clip:280,0,"&hellip;"}
          </p>
      	</div>
	      <?
	        if(count($this->featured_day->moments) >= 8)
		      {
			      $moments = array_slice($this->featured_day->moments, 2, -1);
	          $moments_chunks = array_slice(array_chunk($moments, count($moments) / 5), 0, 5);
		      }
	        else
		        $moments_chunks = array_slice(array_chunk($this->featured_day->moments, 1), 0, 5);
	      ?>
        {{list using="$moments_chunks"}}
          <ul id="preview-list" class="items-list">
            {{list:item}}
              <li>
                <a href="/pages/{$#featured_day->id}/day#moment-id{$item[0].id}">
  	              <img src="{$item[0].image_266}" alt="{$item[0].description}" />
                </a>
              </li>
            {{/list:item}}
          </ul>
        {{/list}}
      </div>
    <?php } ?>

    <div class="row-fluid">
    	<ul class="items-list">
		    <li class="big-item padded">
		      <h2 id="journal"><span class="muted">{{__ text="Journal"}}</span></h2>
			    <ul class="items-list">
				    {{list using="{$#journal_days}"}}
				      {{list:item}}
				        {{apply template="big_day" day="{$item}"/}}
				      {{/list:item}}
				    {{/list}}
				   </ul>
			    <ul class="pager">
				    <? if($this->first_link) { ?>
					    <li class="previous">
						    <a href="/">&larr; {{__ text="Today"}}</a>
					    </li>
				    <? } ?>
				    <? if($this->next_link) { ?>
					    <li class="next">
						    <a href="{$#next_link}#journal">{{__ text="Older"}} &rarr;</a>
					    </li>
				    <? } ?>
			    </ul>
		    </li>
    		<li class="medium-item padded">
			    <h2><span class="muted">{{__ text="Popular"}}</span></h2>
			    <ul class="items-list">
				    <li class="medium-day">
              <h3 class="muted">Facebook</h3>
              <div class="fb-like-box" data-href="https://www.facebook.com/Onedayofmine" data-width="240" data-height="230"
                   data-show-faces="true" data-stream="false" data-show-border="false" data-header="false">
              </div>
					  <? if('ru_RU' == $this->toolkit->getLocale()) { ?>
					    <li class="medium-day">
	              <h3 class="muted">VKontakte</h3>
						    <script type="text/javascript">
							    $(function() {
								    $.getScript("//vk.com/js/api/openapi.js?96", function() {
									    VK.Widgets.Group("vk_groups", {mode: 0, width: "240", height: "150"}, 53796872);
								    });
							    });
						    </script>
	              <div id="vk_groups"></div>
					    </li>
				    <? } ?>
				    <? $title = lmb_i18n('Best working day'); ?>
				    {{apply template="medium_day" day="{$#top_working}" title="$title" icon="cogs"/}}
				    <? $title = lmb_i18n('Best day off'); ?>
				    {{apply template="medium_day" day="{$#top_dayoff}" title="$title" icon="calendar-empty"/}}
				    <? $title = lmb_i18n('Best holiday'); ?>
				    {{apply template="medium_day" day="{$#top_holiday}" title="$title"  icon="gift"/}}
				    <? $title = lmb_i18n('Best trip'); ?>
				    {{apply template="medium_day" day="{$#top_trip}" title="$title" icon="rocket"/}}

		        <li><h3 class="muted">{{__ text="Top days"}}</h3></li>
				    {{list using="$#popular_days" counter="$counter"}}
					    {{list:item}}
						    {{apply template="medium_day" day="$item" additional_class="last-item" /}}
					    {{/list:item}}
				    {{/list}}
			    </ul>
    		</li>
		    <li class="small-item">
			    <h2><span class="muted">{{__ text="New"}}</span></h2>
			    <ul class="items-list">
				    <li><h3 class="muted">&hellip;{{__ text="users"}}</h3></li>
				    {{list using="$#new_users"}}
					    {{list:item}}
					    <li class="user-item">
						    <a href="/pages/{$item.id}/user">
							    <img class="img-circle pull-left" src="{$item.image_192}">
						    </a>
						    <a href="/pages/{$item.id}/user">
							    <h5>{$item.name}</h5>
						    </a>
					    </li>
					    {{/list:item}}
				    {{/list}}
				    <li><h3 class="muted">&hellip;{{__ text="days"}}</h3></li>
				    {{list using="{$#new_days}"}}
				      {{list:item}}
				        {{apply template="small_day" day="{$item}"/}}
				      {{/list:item}}
				    {{/list}}
			    </ul>
		    </li>
    	</ul>
    </div>
  {{/into}}
{{/wrap}}
