<!DOCTYPE html>
<html>
<head>
	<meta property="og:title" content="One Day of Mine - Live the life through other people's eyes"/>
	<meta property="og:type" content="company"/>
	<meta property="og:site_name" content="One Day of Mine - Live the life through other people's eyes"/>
	<meta property="og:description" content="<ul>
	<li>new life for old photos</li>
	<li>easy to use: just click next and enjoy our magic</li>
	<li>look at life through the eyes of different people</li>
	<li>gain interest of other people by publishing days from your life</li>
</ul>"/>
	<meta property="og:url" content="onedayofmine.com"/>
	<meta property="og:image"
				content="https://launchrock-assets.s3.amazonaws.com/facebook-files/LEKBNZBC_1363177046270.png?_=0"/>
</head>
<body>
	<div id="lr-widget" rel="LEKBNZBC"></div>
	<script type="text/javascript" src="//ignition.launchrock.com/ignition-current.min.js"></script>
</body>
</html>