<?
$this->title = "OneDayOfMine";
$this->fb_disabled = false;
$this->menu_disabled = true;
?>
{{wrap with="layout.phtml"}}
{{into slot="content"}}
<div class="hero-unit">
  <div style="position:absolute;top:55px;right:75px;"><img src="/img/1.png"/></div>
	<h1>One Day Of Mine</h1>
	<p>Comming soon...</p>
		<br/>
    <ul class="unstyled">
        <li>
		        <i class="icon-large icon-camera-retro"></i>
            new life for old photos
        </li>
        <li>
            <i class="icon-large icon-magic"></i>
            easy to use: just click next and enjoy our magic
        </li>
        <li>
		        <i class="icon-large icon-eye-open"></i>
            look at life through the eyes of different people
        </li>
        <li>
            <i class="icon-large icon-group"></i>
            gain interest of other people by publishing days from your life
        </li>
        <li>
		        <hr/>
            <i class="icon-large icon-question-sign"></i>
            Do you have any questions? <a href="mailto:welcome@onedayofmine.com">welcome@onedayofmine.com</a>!
        </li>
    </ul>
</div>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
{{/into}}
{{into slot="js_ready"}}
{{/into}}
{{/wrap}}
