<?
$this->menu = '';
$this->title = "Live the life through other people's eyes";
?>
{{wrap with="layout.phtml"}}
{{into slot="meta"}}
<meta property="description" content="Photos without story is just beautiful pictures, we like to share stories, best moments of your life: travels, birthday, parties and other meaningfull events"/>
{{/into}}
{{into slot="css"}}
.box {
float: left;
}
.col1 {
margin-right:15px;
margin-bottom:15px;
width: 266px;
height: 266px;
-webkit-box-shadow: 0px 1px 3px rgba(50, 50, 50, 0.73);
-moz-box-shadow:    0px 1px 3px rgba(50, 50, 50, 0.73);
box-shadow:         0px 1px 3px rgba(50, 50, 50, 0.73);
}
.col2 {
width: 562px;
height: 562px
}
.col2 > img {
width:547px;
height:547px;
-webkit-box-shadow: 0px 1px 3px rgba(50, 50, 50, 0.73);
-moz-box-shadow:    0px 1px 3px rgba(50, 50, 50, 0.73);
box-shadow:         0px 1px 3px rgba(50, 50, 50, 0.73);
}
.text {

background:#fff;
color:#333;
}
.text > div {
width:100%;
height:100%;
}
{{/into}}
{{into slot="js_ready"}}
{{/into}}
{{into slot="content"}}
<div id="gallery">
	<div class="box col2">
		<img src="https://onedayofmine.s3.amazonaws.com/days/3/292d46aa9b459ac85b65c5ea69aacbe07db4fe02_532.jpeg" />
	</div>
	<div class="box col2">
		<div class="box text col1">
			<div style="padding:0 10px">
				<h2>Give new life for old photos</h2>
				<p>People have tons of photos that lost in time, give them new life, make stories out of them and share them with friends.</p>
				<a class="btn btn-success trigger_login" href="/pages/import">Try it!</a>
			</div>
		</div>
		<div class="box col1"><img src="//onedayofmine.s3.amazonaws.com/days/f968e57050673e6032f702c259362e65e7f2ff2b_266.jpeg" /></div>
		<div class="box col1"><img src="//onedayofmine.s3.amazonaws.com/days/3/8dfaca7be9dff98458cede9eb288b2c62137ba12_266.jpeg" /></div>
		<div class="box col1"><img src="//onedayofmine.s3.amazonaws.com/days/3/90d1f95bda348c58afdb89a8878489deab7c8967_266.jpeg" /></div>
	</div>

	<br style="clear:both"/>

	<div class="box col2">
		<div class="box col1"><img class="image-polaroid" src="https://onedayofmine.s3.amazonaws.com/days/f968e57050673e6032f702c259362e65e7f2ff2b_266.jpeg" /></div>
		<div class="box col1">
			<div style="padding:0 10px">
				<h2>Share a story, not photo</h2>
				<p>Photos without story is just beautiful pictures, we like to share stories, best moments of your life: travels, birthday, parties and other meaningfull events. </p>
				<a class="btn btn-success trigger_login" href="/pages/import">Try it!</a>
			</div>
		</div>
		<div class="box col1"><img class="image-polaroid" src="https://onedayofmine.s3.amazonaws.com/days/f968e57050673e6032f702c259362e65e7f2ff2b_266.jpeg" /></div>
		<div class="box col1"><img class="image-polaroid" src="https://onedayofmine.s3.amazonaws.com/days/f968e57050673e6032f702c259362e65e7f2ff2b_266.jpeg" /></div>
	</div>
	<div class="box col2"><img style="width:542px;height:542px" src="//onedayofmine.s3.amazonaws.com/days/10/0ed9d7de38d044ae7ce37757438b85f8cd80e9c1_532.jpeg" /></div>

	<br style="clear:both"/>

	<div class="box col2"><img style="width:542px;height:542px" src="//onedayofmine.s3.amazonaws.com/days/10/0ed9d7de38d044ae7ce37757438b85f8cd80e9c1_532.jpeg" /></div>
	<div class="box col2">
		<div class="box text col1">
			<div style="padding:0 10px">
				<h2>Magic</h2>
				<p>It’s an easy-to-use tool, just connect your social profiles and enjoy the magic.</p>
				<a class="btn btn-success trigger_login" href="/pages/import">Try it!</a>
			</div>
		</div>
		<div class="box col1"><img src="//onedayofmine.s3.amazonaws.com/days/f968e57050673e6032f702c259362e65e7f2ff2b_266.jpeg" /></div>
		<div class="box col1"><img src="//onedayofmine.s3.amazonaws.com/days/3/8dfaca7be9dff98458cede9eb288b2c62137ba12_266.jpeg" /></div>
		<div class="box col1"><img src="//onedayofmine.s3.amazonaws.com/days/3/90d1f95bda348c58afdb89a8878489deab7c8967_266.jpeg" /></div>
	</div>

</div>
{{/into}}
{{/wrap}}
