<?
$this->menu = '';
?>
{{wrap with="layout.phtml"}}
  {{into slot="css"}}
    .sign-up-wrap {
      padding-bottom: 100px;
    }

    .select-wrap {
      margin-top: 1px;
    }

    .carousel-caption {
      height: 50px;
      padding-bottom: 0px;
      padding-top: 40px;
      bottom: -20px;
    }

    .carousel-control {
      top: 48%
    }

    .carousel-inner {
      width: 1000px;
      max-width: 100%;
    }

    .carousel-blocks {
      height:400px;
      overflow:hidden;
    }

    .carousel-blocks {
      /*width: 120%;*/
    }

    .carousel-blocks img {
      width: 200px;
      height: 200px;
      float:left;
      display:inline-block;
    }

    .carousel-blocks img.big {
      width: 400px;
      height: 400px;
    }

    .carousel-caption,
    .carousel-caption-overlap,
    .day-final-comment a {
      color: #FFF;
    }

    .select-wrap .caret {
      border-top: 4px solid #FFF;
      vertical-align: 30%;
      margin-right: 5px;
    }

    .select-wrap .select-representation {
      border-bottom: 1px dotted #FFF;
    }

    .select-wrap .select-representation,
    .select-wrap select {
      height: 20px;
    }

    .select-wrap .select-representation,
    .select-wrap .select-value {
      display: inline-block;
    }

    .carousel-caption .day-final-comment {
      text-overflow: ellipsis; /* … */
      overflow:hidden;
      white-space: nowrap;
      display: inline-block;
      max-width: 90%;
      height: 20px;
    }

    .carousel-caption-overlap {
      position: absolute;
      bottom: 35px;
      left: 80px;
    }

    .carousel-caption-overlap .icon-random {
      vertical-align: middle;
      margin-left: 10px;
    }
  {{/into}}
  {{into slot="js"}}
    var interesting_days = <?= json_encode($this->interesting_days); ?>;
  {{/into}}
  <script>
  {{into slot="js_ready"}}
    // Nice boostrap select's
    $(function() {
      function resetHiddenSelect(wrapper_selector) {
        var $selector = wrapper_selector.find('select');
        var $value_container = wrapper_selector.find('.select-representation');
        var $value = wrapper_selector.find('.select-value');

        $value.text($selector.val());
        $selector.width($value_container.width());
      }

      var carousel_caption_overlap = $('.carousel-caption-overlap');

      carousel_caption_overlap.find('.select-wrap').each(function() {
        var $this = $(this);
//        resetHiddenSelect($this);
//
//        $this.find('select').change(function() {
//          resetHiddenSelect($this);
//        });
      });

      // $('#days_carousel').on('slide', function(event) {
      //   carousel_caption_overlap.css('white-space', 'nowrap');
      //   carousel_caption_overlap.animate({
      //     left: '-50px'
      //   }, function() {
      //     carousel_caption_overlap.css('left', '100%').animate({
      //       left: '80px'
      //     }, function() {
      //       carousel_caption_overlap.css('white-space', 'interhit');
      //     });
      //   });
      // });

      // TODO: animate change when next element have different value
      $('#days_carousel').on('slid', function(event) {
        var active_item = $(this).find('.item.active');
	      $('.dayType').html(active_item.data().type);
	      $('.userOccupation').html(active_item.data().userOccupation);
	      $('.userLocation').html(active_item.data().userLocation);
      });
    });

    (function() {
      function fixFinalCommentEndings() {
        $('#days_carousel .day-final-comment small').each(function() {
          var text = $(this).text().trim();
          if(text.substring(text.length-1) !== '.') {
            $(this).text(text + '.');
          }
        });
      }

      $(function() {
        fixFinalCommentEndings();

        // IDEA: animate all blocks with different animation speed
        $('#days_carousel').carousel({ interval: 5000 });
      });
    })();
  {{/into}}
  </script>
  {{into slot="content"}}
    <h1>One Day Of Mine</h1>
    <p class="lead">Live the life through other people's eyes</p>

    {{list using="$#interesting_days" counter="$i"}}
      <div class="row-fluid hide-phone">
        <div id="days_carousel" class="carousel slide block-center span12">
          <div class="carousel-inner block-center">
            {{list:item}}
              <div class="item<?php if($i == 1) { ?> active<? } ?>" data-type="{$item.type}" data-user-occupation="{$item.user.occupation}" data-user-location="{$item.user.location}">
                <div class="carousel-blocks">
                  {{list using="$item.moments" as="$moment" counter="$counter"}}
                    {{list:item}}
                      <?php if($counter == 1) { ?>
                        <img src="{$moment.image_532}" class="big" />
                      <? } else { ?>
                        <img src="{$moment.image_266}" />
                      <? } ?>
                    {{/list:item}}
                  {{/list}}
                </div>
                <div class="carousel-caption">
                  <div class="day-final-comment">
                    <a href="/pages/{$item.id}/day">
                      <small>{$item.final_description}</small>
                      &rarr;
                    </a>
                  </div>
                </div>
              </div>
            {{/list:item}}
          </div>
          <div class="carousel-caption-overlap">
            <div class="selector">
              <span class="dayType">{$item.type}</span>
              of
              <span class="userOccupation">{$#interesting_days[0].user.occupation}</span>
              from
              <span class="userLocation">{$#interesting_days[0].user.location}</span>
            </div>
          </div>
          <a class="left carousel-control" href="#days_carousel" data-slide="prev">‹</a>
          <a class="right carousel-control" href="#days_carousel" data-slide="next">›</a>
        </div>
      </div>
    {{/list}}

		<hr />

    <div class="row-fluid">
     <div class="span4">
        <h2>Share a story, not photo</h2>
        <p>Photos without story is just beautiful pictures, we like to share stories, best moments of your life: travels, birthday, parties and other meaningfull events. </p>
     </div>
      <div class="span4">
        <h2>Give new life for old photos</h2>
        <p>People have tons of photos that lost in time, give them new life, make stories out of them and share them with friends.</p>
      </div>
      <div class="span4">
        <h2>Magic</h2>
        <p>It’s an easy-to-use tool, just connect your social profiles and enjoy the magic.</p>
     </div>
    </div>

  {{/into}}
{{/wrap}}
