{{wrap with="layout.phtml"}}
{{into slot="content"}}
        <div>
            <h2>Instagram &rarr; Facebook</h2>

            <div style="margin-bottom: 20px">Import your days from Instagram to Facebook</div>

            <div class="progress progress-striped" style="display:none">
                <div class="bar" style="width: 0%;"></div>
            </div>

            <a href="https://api.instagram.com/oauth/authorize/?client_id={$#instagram.client_id}&redirect_uri={$#instagram.redirect_url}&response_type=token"
               class="btn btn-primary btn-large" style="display:none">
                Step 1 of 3 <i class="icon-white icon-forward"></i>
            </a>

            <div class="well-large cant" style="display:none">Sorry. You have no days with 3 or more photos</div>

            <div class="days"></div>
        </div>
{{/into}}
{{into slot="js_include"}}
	<script id="day-item" type="text/x-handlebars-template">
      <div day_pos="[[day_position]]" class="well">
	      <h4 class="time">[[time]]</h4>
	      <ul class="thumbnails">
				[[#moments]]
	          <li style="width:160px;">
		          <div class="thumbnail">
				          <img src="[[images.thumbnail.url]]" class="img-rounded"/>
				          <p><small>[[caption.text]]</small></p>
				          <center>
						          <button class="btn btn-warning remove-photo-action" moment_id="[[id]]">Remove</button>
				          </center>
		          </div>
	          </li>
		    [[/moments]]

	      </ul><br/>
	      <button class="btn btn-primary btn-large export-action">
	        Step 2 of 3 <i class="icon-white icon-forward"></i> </button>
      </div>
	</script>
	<script src="/lib/handlebars.js"></script>
	<script src="/lib/Importer.js"></script>
{{/into}}
{{into slot="js_ready"}}
    hash = window.location.hash.substr(14);
    $(document).ready(function () {
        if (window.location.hash.length < 2) {
            $('a.btn').show();
        }
        else {
            Importer.import(hash);
        }
    });
{{/into}}
{{/wrap}}
