<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Intagram &rarr; Facebook</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
        body {
            padding-bottom: 40px;
        }

        .container-narrow { margin: 0 auto; max-width: 700px; }
        .container-narrow > hr { margin: 30px 0;}

        .progress { height:30px; font-size: 36px; margin:50px 0; }

        h4 {
            background-color: #aaa;
            -webkit-background-clip: text;
            -moz-background-clip: text;
            background-clip: text;
            color: transparent;
            text-shadow: rgba(255,255,255,0.5) 0px 2px 2px;
        }

        .jumbotron {
            text-align: center;
        }

        .jumbotron h1 {
            font-size: 72px;
            line-height: 1;
        }

        .jumbotron .btn {
            font-size: 21px;
            padding: 14px 24px;
        }

        .days ul {
		        list-style: none;
		        padding-bottom: 20px;
        }

		    .days ul li {
				    float:left;
		    }

		    .days br {
				    clear:both;
		    }


    </style>
    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">
</head>

<body>
<div class="container">
    <div class="container-narrow">

        <div class="jumbotron">
            <h2>Instagram &rarr; Facebook</h2>
	          <div>Import your days from Instagram to Facebook</div>

            <div class="progress progress-striped" style="display:none">
                <div class="bar" style="width: 0%;"></div>
            </div>

            <a href="https://api.instagram.com/oauth/authorize/?client_id={$#instagram.client_id}&redirect_uri={$#instagram.redirect_url}&response_type=token"
               class="btn btn-primary btn-large"  style="display:none">
                Start <i class="icon-white icon-play"></i>
            </a>

            <div class="well well-small" style="display:none">Sorry. You have no days with 3 or more photos</div>

            <div class="days"></div>
        </div>
    </div>
    <!-- /container -->

    <script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/jquery.js"></script>
    <script type="text/javascript">
        if (window.location.hash.length < 2) {
            $('a.btn').show();
        }
        else {
		        $('.progress').show();
            var hash = window.location.hash.substr(14);
            var photos_count = 0;
            var photos = [];
            var $days = $('.days');
            $.ajax({
                dataType:"json",
                url:'https://api.instagram.com/v1/users/50699135/?callback=?',
                data:{
                    access_token:hash
                },
                cache:true,
                success:function (user_response) {
                    photos_count = user_response.data.counts.media;
                    $('.bar').css('width', '10%');
                    getPhotos(photos_count, 'https://api.instagram.com/v1/users/50699135/media/recent/?access_token=' + hash + '&count=40&callback=?', function () {
                        var current_day = [photos.shift()];
                        for (i in photos) {
                            var prev_photo = current_day[current_day.length - 1];
                            var photo = photos.shift();
                            if ((prev_photo.created_time - photo.created_time) < 4 * 60 * 60)
                                current_day.push(photo);
                            else {
                                $('.bar').css('width', "" + 90 + ((photos_count - photos.length) / photos_count * 0.1) + '%');
                                if (current_day.length > 3) {
		                                var out = '<div class="well"><h4>' + (new Date(current_day[current_day.length - 1].created_time * 1000)).toLocaleDateString() +
						                                '</h4><ul>';
						                        for(p in current_day)
						                        {
																			out += '<li><img src="'+current_day[p].images.thumbnail.url+'"></li>';
						                        }

		                                out += '</ul><br/>';
		                                out += '<div style="margin:20px"><a href="#" class="btn btn-primary btn-large"><i class="icon-white icon-thumbs-up"></i> Post to Facebook</a></p>';
																		$days.append(out + "</div>");

                                }
                                current_day = [photos.shift()];
                            }
                        }

		                    $('.progress').hide();
                    });
                }
            });

		        function formatDate(photo) {
				        return (new Date(photo.created_time * 1000)).toLocaleString();
		        }

            function getPhotos(photos_count, url, callback) {
                $.ajax({
                    dataType:"json",
                    url:url,
                    cache:true,
                    success:function (photos_resp) {
                        photos = photos.concat(photos_resp.data);
                        $('.bar').css('width', "" + (10 + photos.length / photos_count * 70) + "%");
                        if (typeof photos_resp.pagination.next_max_id != 'undefined')
                            getPhotos(photos_count, url + '&max_id=' + photos_resp.pagination.next_max_id, callback);
                        else
                            callback();
                    }
                });
            }
        }
    </script>
</body>
</html>
