<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Import from Intagram</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
        body {
            padding-bottom: 40px;
        }

            /* Custom container */
        .container-narrow {
            margin: 0 auto;
            max-width: 700px;
        }

        .container-narrow > hr {
            margin: 30px 0;
        }

            /* Main marketing message and sign up button */
        .jumbotron {
            text-align: center;
        }

        .jumbotron h1 {
            font-size: 72px;
            line-height: 1;
        }

        .jumbotron .btn {
            font-size: 21px;
            padding: 14px 24px;
        }
    </style>
    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">
</head>

<body>
<div class="container">
    <div class="container-narrow">

        <div class="jumbotron">
            <h1>Import your photos from Instagram!</h1>

            {{slot id='content'/}}
        </div>
    </div>
    <!-- /container -->

    <script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/jquery.js"></script>
    <script type="text/javascript">
        if(window.location.hash.length > 1)
        {
            $('a.btn').hide();
            var hash = window.location.hash.substr(14);
            $.ajax('/import/instagram?code=' + hash).done(function(data) {
                console.log(data);
            });
        }
    </script>
</body>
</html>
