# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.synced_folder "../../", "/vagrant/odom"
  config.vm.network :forwarded_port, guest: 80, host: 8888
  config.vm.provision :shell, :path => "bootstrap.sh"
end
