# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu-server-12042-x64-vbox4210"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box"

  config.vm.network :public_network, mac: "0800272AFF18"

  config.vm.synced_folder "../../", "/www/onedayofmine", :extra => "dmode=777,fmode=777"
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.provision :shell, :inline => "sudo apt-get update && sudo apt-get install puppet -y"

  config.vm.provision :puppet do |puppet|
  	puppet.module_path = "modules"
		puppet.manifest_file = "site.pp"
  end

  config.vm.provider "virtualbox" do |v|
    v.name = "ODOM-dev"
  end

end
