{{wrap with="admin_page_layout.phtml" in="content_zone"}}

  {{include file="_admin/selectors.phtml"/}}
  {{include file="_admin_object/actions.phtml"/}}

  <div id="header">
    <h1>Days</h1>
    {{include file='_admin/pager.phtml' items='{$this->items}'/}}
  </div>

  <div id="body">

    {{list using="{$this->items}" as="$item" counter="$counter" parity='$parity'}}

      <div class='list'>
        <div class='list_actions'>
          {{apply template="selectors_button" action="delete" title="Удалить" /}}
        </div>
        <table>
          <tr class="$parity">
            <th>{{apply template="selectors_toggler"/}}</th>
            <th>id
            {{include file='_admin/sort_by_column.phtml' field='id'/}}
            </th>
            <th>User
            {{include file='_admin/sort_by_column.phtml' field='user_id'/}}
            </th>
            <th>Title
            {{include file='_admin/sort_by_column.phtml' field='title'/}}
            </th>
	          <th>Moments Count</th>
            <th>Likes count
            {{include file='_admin/sort_by_column.phtml' field='likes_count'/}}
            </th>
	          <th>Views count
		          {{include file='_admin/sort_by_column.phtml' field='views_count'/}}
	          </th>
            <th>ctime
            {{include file='_admin/sort_by_column.phtml' field='ctime'/}}
            </th>
            <th>utime
            {{include file='_admin/sort_by_column.phtml' field='utime'/}}
            </th>
            <th>Deleted
            {{include file='_admin/sort_by_column.phtml' field='is_deleted'/}}
            </th>
            <th>Действия</th>
          </tr>

          {{list:item}}
            <tr class="{$parity}">
              <td>{{apply template="selector" value="{$item.id}"/}}</td>
              <td>{$item.id}</td>
              <td><a href="/pages/{$item->getUser()->id}">{$item->getUser()->name}</a></td>
              <td><a href="/pages/{$item.id}/day">{$item.title}</a></td>
	            <td>{$item->getMoments()->count()}</td>
              <td>{$item->getLikes()->count()}</td>
	            <td>{$item.views_count}</td>
              <td>{$item.ctime|date:"d.m.Y H:i:s"}</td>
              <td>{$item.utime|date:"d.m.Y H:i:s"}</td>
              <td>{$item.is_deleted}</td>
              <td class='actions'>
                {{apply template="object_action_delete" item="{$item}"/}}
	              {{apply template="object_action_edit" item="{$item}"/}}
              </td>
            </tr>
          {{/list:item}}
          {{list:empty}}
            <div class="empty_list">Day отсутствуют</div>
          {{/list:empty}}
        </table>
        <div class='list_actions'>
          {{apply template="selectors_button" action="delete" title="Удалить" /}}
        </div>
      </div>

    {{/list}}

  </div>

{{/wrap}}
