{{wrap with="admin_modal_page_layout.phtml" into="content_zone"}}
{{form id='object_form' name='user_form' method='post' enctype="multipart/form-data"}}

<h1>Add day to rating</h1>

{{include file='_admin/form_errors.phtml'/}}

<div class='tabs'>

  <ul>
    <li id='properties'><a>Properties</a></li>
  </ul>

  <div id="tab_properties">

    <dl class="field">
      <dt>{{label for="day_id"}}Day id:{{/label}}</dt>
      <dd>{{input id="day_id" name="day_id" type="text" title="day_id"/}}</dd>
    </dl>

    <dl class="field">
      <dt>{{label for="rating"}}Rating:{{/label}}</dt>
      <dd>{{input id="rating" name="rating" type="text" title="rating"/}}</dd>
    </dl>

    <dl class="field">
      <dt>{{label for="is_pinned"}}pinned:{{/label}}</dt>
      <dd>{{js_checkbox id="is_pinned" name="is_pinned" title="is_pinned"/}}</dd>
    </dl>

  </div>

</div>

{{include file='_admin/form_buttons.phtml'/}}

{{/form}}
{{/wrap}}
