{{wrap with="admin_page_layout.phtml" in="content_zone"}}

  {{include file="_admin/selectors.phtml"/}}
  {{include file="_admin_object/actions.phtml"/}}

  <div id="header">
    <h1>Interesting days</h1>
    <div class="header_actions">
	    <a href='/admin_day/interesting_recalc/' title="Recalc" class="thickbox"><img src='/shared/cms/images/icons/arrow_refresh.png'/> Recalc</a>
	    <a href='/admin_day/interesting_add/' title="Add" class="thickbox"><img src='/shared/cms/images/icons/add.png'/> Add</a>
    </div>
  </div>

  <div id="body">

    {{list using="{$#items}" as="$item" counter="$counter" parity='$parity'}}

      <div class='list'>
        <div class='list_actions'>
          {{apply template="selectors_button" action="delete" title="Удалить" /}}
        </div>
        <table>
          <tr>
            <th>{{apply template="selectors_toggler"/}}</th>
            <th>Day</th>
            <th>User</th>
            <th>Title</th>
            <th>Likes</th>
	          <th>Age</th>
            <th>Rating</th>
	          <th>Is pinned</th>
            <th>Actions</th>
          </tr>

          {{list:item}}
            <tr class="{$parity}">
              <td>{{apply template="selector" value="{$item.id}"/}}</td>
              <td>{$item.id}</td>
              <td><a href="/pages/{$item->getDay()->getUser()->id}/user">{$item->getDay()->getUser()->name}</a></td>
	            <td><a href="/pages/{$item->getDay().id}/day">{$item->getDay().title}</a></td>
              <td>{$item->getDay()->getLikes()->count()|default:0}</td>
	            <td>{$item->getDay().ctime}</td>
              <td>{$item.rating}</td>
	            <td>
		            <?php if($item['is_pinned']) { ?>
			            <img title="yes" src='/shared/cms/images/icons/lightbulb.png'/>
		            <? } else { ?>
			            <img title="no" src='/shared/cms/images/icons/lightbulb_off.png'/>
		            <? } ?>
	            </td>
              <td class='actions'>
                <?php if($item['is_pinned']) { ?>
		              <a href='/admin_day/interesting_unpin/{$item.id}' title="unpin" class="thickbox"><img src='/shared/cms/images/icons/link_break.png'/></a>
                <?php } else { ?>
		              <a href='/admin_day/interesting_pin/{$item.id}' title="pin" class="thickbox"><img src='/shared/cms/images/icons/link.png'/></a>
                <?php } ?>
	              <a href='/admin_day/interesting_edit/{$item.id}' title="edit" class="thickbox"><img src='/shared/cms/images/icons/pencil.png'/></a>
                <a href='#' onclick="if(confirm('{{i18n text="Remove day from interesting" domain="cms"/}}?')) {jQuery.post('/admin_day/interesting_delete', {ids:{$item.id}}, function(){document.location.reload()})}" title="Delete">
                  <img src='/shared/cms/images/icons/cancel.png'/>
                </a>
              </td>
            </tr>
          {{/list:item}}
          {{list:empty}}
            <div class="empty_list">Рейтинг пуст!</div>
          {{/list:empty}}
        </table>
        <div class='list_actions'>
          {{apply template="selectors_button" action="delete" title="Удалить" /}}
        </div>
      </div>

    {{/list}}

  </div>

{{/wrap}}
